---
title: "Descriptive statistics about the economic literature on quality"
output:
  html_document:
    code_folding: hide
---


<style type="text/css">
.main-container {
  max-width: 1400px;
  margin-left: auto;
  margin-right: auto;
}
</style>



# 1- Most quoted items by decades

## 1.1- 1980-1989

```{r}





setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")


load("Data_7_finalbase.rda")


#####################################################################################################################
#####################################################################################################################
# Modification qualitative d'erreurs restantes constatées en explorant la base: Can be continued -------------------
#####################################################################################################################
#####################################################################################################################


eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1966) 74  65) 132"]<-"LANCASTER (1966) 74 132"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1966) AB 74"]<-"LANCASTER (1966) 74 132"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1971) AB 40"]<-"LANCASTER (1971) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1972) AB AB"]<-"LANCASTER (1971) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER , 1971. AB AB"]<-"LANCASTER (1971) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1980) 116 281"]<-"LANCASTER (1979) AB AB"        
eoeoe$identifiant[eoeoe$identifiant=="AKERLOF (1970) AB 89"]<-"AKERLOF (1970) 84 488"
eoeoe$identifiant[eoeoe$identifiant=="AKERLOF (1970) AB AB"]<-"AKERLOF (1970) 84 488"
eoeoe$identifiant[eoeoe$identifiant=="MUSSA (1978) AB AB"]<-"MUSSA (1978) 18 301"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (1985) AB AB"]<-"BAGWELL (1988) 19 59"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (2007) AB AB"]<-"BAGWELL (2007) 3 1701"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (1988) AB AB"]<-"BAGWELL (1991) 81 224"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (1991) 81 . AB"]<-"BAGWELL (1991) 81 224"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL 1991 81 AB"]<-"BAGWELL (1991) 81 224"
eoeoe$identifiant[eoeoe$identifiant=="TIROLE (1990) AB AB"]<-"TIROLE (1988) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="TIROLE (1994) AB AB"]<-"TIROLE (1988) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="TIROLE (1998) AB AB"]<-"TIROLE (1988) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="SPENCE (1973) AB AB"]<-"SPENCE (1973) 87 355"


# On calcule la fréquence de chaque identifiant

freq<-table(eoeoe$identifiant)
freq<-as.data.frame(freq)

# On stocke la fréquence comme nouvelle variable, ce qui nous servira à renseigner la taille des noeuds dans les graphes

eoeoe$frequence<-0
for(i in 1:nrow(eoeoe)){
  j<-which(eoeoe$identifiant[i] == freq$Var1)
  eoeoe$frequence[i]<-freq$Freq[j]
}



load("./Data_5_nodes.rda")


desco$Datepubli<-as.character(desco$Datepubli)
eoeoe$anneecitant<-0
for(i in 1:nrow(eoeoe)){
  j<-which(eoeoe$V2[i] == desco$Cartel)
  eoeoe$anneecitant[i] <- desco$Datepubli[j]
}


library(readr)
library(stringr)

eoeoe$anneecitant<-str_replace_all(string = eoeoe$anneecitant, pattern = "\\(", replacement = "")
eoeoe$anneecitant<-str_replace_all(string = eoeoe$anneecitant, pattern = "\\)", replacement = "")
eoeoe$anneecitant<-as.numeric(eoeoe$anneecitant)


freq19811990<-eoeoe[eoeoe$anneecitant==1980|eoeoe$anneecitant==1981|eoeoe$anneecitant==1982|eoeoe$anneecitant==1983|eoeoe$anneecitant==1984|eoeoe$anneecitant==1985|eoeoe$anneecitant==1986|eoeoe$anneecitant==1987|eoeoe$anneecitant==1988|eoeoe$anneecitant==1989,]
freq19912000<-eoeoe[eoeoe$anneecitant==1990|eoeoe$anneecitant==1991|eoeoe$anneecitant==1992|eoeoe$anneecitant==1993|eoeoe$anneecitant==1994|eoeoe$anneecitant==1995|eoeoe$anneecitant==1996|eoeoe$anneecitant==1997|eoeoe$anneecitant==1998|eoeoe$anneecitant==1999,]
freq20012010<-eoeoe[eoeoe$anneecitant==2000|eoeoe$anneecitant==2001|eoeoe$anneecitant==2002|eoeoe$anneecitant==2003|eoeoe$anneecitant==2004|eoeoe$anneecitant==2005|eoeoe$anneecitant==2006|eoeoe$anneecitant==2007|eoeoe$anneecitant==2008|eoeoe$anneecitant==2009,]
freq20112020<-eoeoe[eoeoe$anneecitant==2010|eoeoe$anneecitant==2011|eoeoe$anneecitant==2012|eoeoe$anneecitant==2013|eoeoe$anneecitant==2014|eoeoe$anneecitant==2015|eoeoe$anneecitant==2016|eoeoe$anneecitant==2017|eoeoe$anneecitant==2018|eoeoe$anneecitant==2019,]

freq19811990<-table(freq19811990$identifiant)
freq19811990<-as.data.frame(freq19811990)

freq19912000<-table(freq19912000$identifiant)
freq19912000<-as.data.frame(freq19912000)

freq20012010<-table(freq20012010$identifiant)
freq20012010<-as.data.frame(freq20012010)

freq20112020<-table(freq20112020$identifiant)
freq20112020<-as.data.frame(freq20112020)




top19811990<-freq19811990[rev(order(freq19811990$Freq)),]
top19912000<-freq19912000[rev(order(freq19912000$Freq)),]
top20012010<-freq20012010[rev(order(freq20012010$Freq)),]
top20112020<-freq20112020[rev(order(freq20112020$Freq)),]


top19811990<-top19811990[1:nrow(top19811990),]
top19912000<-top19912000[1:nrow(top19912000),]
top20012010<-top20012010[1:nrow(top20012010),]
top20112020<-top20112020[1:nrow(top20112020),]



row.names(top19811990)<-1:nrow(top19811990)
row.names(top19912000)<-1:nrow(top19912000)
row.names(top20012010)<-1:nrow(top20012010)
row.names(top20112020)<-1:nrow(top20112020)


top19811990<-top19811990[1:25,]
top19912000<-top19912000[1:25,]
top20012010<-top20012010[1:25,]
top20112020<-top20112020[1:25,]


for(i in 1:nrow(top19811990)){
  j<-which(top19811990$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top19811990$V1[i] <- eoeoe$V1[j[z]]
}


for(i in 1:nrow(top19912000)){
  j<-which(top19912000$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top19912000$V1[i] <- eoeoe$V1[j[z]]
}

for(i in 1:nrow(top20012010)){
  j<-which(top20012010$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top20012010$V1[i] <- eoeoe$V1[j[z]]
}

for(i in 1:nrow(top20112020)){
  j<-which(top20112020$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top20112020$V1[i] <- eoeoe$V1[j[z]]
}



top19811990<-top19811990[,c(3)]
top19912000<-top19912000[,c(3)]
top20012010<-top20012010[,c(3)]
top20112020<-top20112020[,c(3)]


top19811990<-as.data.frame(top19811990)
top19912000<-as.data.frame(top19912000)
top20012010<-as.data.frame(top20012010)
top20112020<-as.data.frame(top20112020)



names(top19811990)[names(top19811990) == "top19811990"] <- "Most quoted references 1980-1989"
names(top19912000)[names(top19912000) == "top19912000"] <- "Most quoted references 1990-1999"
names(top20012010)[names(top20012010) == "top20012010"] <- "Most quoted references 2000-2009"
names(top20112020)[names(top20112020) == "top20112020"] <- "Most quoted references 2010-2019"





for(i in 1:nrow(top19811990)){
  top19811990$`Most quoted references 1980-1989`[i]<-paste(i,"-",top19811990$`Most quoted references 1980-1989`[i])
}

for(i in 1:nrow(top19912000)){
  top19912000$`Most quoted references 1990-1999`[i]<-paste(i,"-",top19912000$`Most quoted references 1990-1999`[i])
}

for(i in 1:nrow(top20012010)){
  top20012010$`Most quoted references 2000-2009`[i]<-paste(i,"-",top20012010$`Most quoted references 2000-2009`[i])
}


for(i in 1:nrow(top20112020)){
  top20112020$`Most quoted references 2010-2019`[i]<-paste(i,"-",top20112020$`Most quoted references 2010-2019`[i])
}





library(knitr)
library(kableExtra)


kable(top19811990)



```

## 1.2- 1990-1999

```{r}

kable(top19912000)


```

## 1.3- 2000-2009

```{r}

kable(top20012010)

```

## 1.4- 2010-2019


```{r}

kable(top20112020)

```

## 1.5- Summary chart


```{r, message = FALSE}


top19811990<-freq19811990[rev(order(freq19811990$Freq)),]
top19912000<-freq19912000[rev(order(freq19912000$Freq)),]
top20012010<-freq20012010[rev(order(freq20012010$Freq)),]
top20112020<-freq20112020[rev(order(freq20112020$Freq)),]


top19811990<-top19811990[1:nrow(top19811990),]
top19912000<-top19912000[1:nrow(top19912000),]
top20012010<-top20012010[1:nrow(top20012010),]
top20112020<-top20112020[1:nrow(top20112020),]



top19811990$Freq<-1:nrow(top19811990)
top19912000$Freq<-1:nrow(top19912000)
top20012010$Freq<-1:nrow(top20012010)
top20112020$Freq<-1:nrow(top20112020)


top19811990$YEAR<-"1980-1989"
top19912000$YEAR<-"1990-1999"
top20012010$YEAR<-"2000-2009"
top20112020$YEAR<-"2010-2019"


top19811990<-top19811990[1:25,]
top19912000<-top19912000[1:25,]
top20012010<-top20012010[1:25,]
top20112020<-top20112020[1:25,]


top<-rbind(top19811990,top19912000,top20012010,top20112020)

library(ggplot2)
library(dplyr)


top$Var1<-str_replace_all(string = top$Var1, pattern = "D'ASPREMONT", replacement = "DASPREMONT")

top$Var1<-str_replace_all(string = top$Var1, pattern = " [[:digit:]].*$", replacement = "")

top$Var1<-str_replace_all(string = top$Var1, pattern = " AB.*$", replacement = "")




my_theme <- function() {
  
  # Colors
  color.background = "white"
  color.text = "#22211d"
  
  # Begin construction of chart
  theme_bw(base_size=15) +
    
    # Format background colors
    theme(panel.background = element_rect(fill=color.background,
                                          color=color.background)) +
    theme(plot.background  = element_rect(fill=color.background,
                                          color=color.background)) +
    theme(panel.border     = element_rect(color=color.background)) +
    theme(strip.background = element_rect(fill=color.background,
                                          color=color.background)) +
    
    # Format the grid
    theme(panel.grid.major.y = element_blank()) +
    theme(panel.grid.minor.y = element_blank()) +
    theme(axis.ticks       = element_blank()) +
    
    # Format the legend
    theme(legend.position = "none") +
    
    # Format title and axis labels
    theme(plot.title       = element_text(color=color.text, size=5, face = "bold")) +
    theme(axis.title.x     = element_text(size=0, color="black", face = "bold")) +
    theme(axis.title.y     = element_text(size=0, color="black", face = "bold",
                                          vjust=1.25)) +
    theme(axis.text.x      = element_text(size=0, vjust=0.5, hjust=0.5,
                                          color = color.text)) +
    ### Taille des nombre
    theme(axis.text.y      = element_text(size=2.5, color = color.text)) +
    theme(strip.text       = element_text(face = "bold")) +
    
    # Plot margins
    # Contour du graphique
    theme(plot.margin = unit(c(0, 0.2, 0.3, 0), "cm"))
}




library(ggiraph)



gg_point=ggplot(top,aes(x = as.factor(YEAR), y = Freq, group = Var1)) +
  # Taille des lignes
  geom_line_interactive(aes(color = Var1, alpha = 1,tooltip=Var1, data_id = Var1), size = 0.3) +
  # Taille des points
  geom_point_interactive(aes(x = as.factor(YEAR), y = Freq, group = Var1, color = Var1, alpha = 1, tooltip = Var1, data_id = Var1), size = 1) +
  geom_point_interactive(color = "#FFFFFF", size = 0.01) +
  scale_y_reverse(breaks = 1:table(top$YEAR)[[1]]) + 
  scale_x_discrete(breaks = 1:length(table(top$YEAR))) +
  theme(legend.position = 'none') +
  # le x designe le positionnement des auteurs à gauche
  geom_text(data = top %>% filter(YEAR == "1980-1989"),
            aes(label = Var1, x = 0.42) , hjust = 0.0,
            fontface = "bold", color = "#888888", size = 0.7) +
  # idem mais à droite
  geom_text(data = top %>% filter(YEAR == "2010-2019"),
            aes(label = Var1, x = 4.5) , hjust = 1.0,
            fontface = "bold", color = "#888888", size = 0.7) +
  labs(x = '', y = '', title = 'Most quoted references (1980-1989, 1990-1999, 2000-2009, 2010-2019)') +
  my_theme() 




girafe(ggobj = gg_point, width_svg = 3, height_svg = 2,
       options = list(
         opts_hover_inv(css = "opacity:0.1;"),
         opts_hover(css = "stroke-width:2;")
       ))






```



# 2- Most quoted authors by decades


## 2.1- Table

```{r}


setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")


load("Data_7_finalbase.rda")


#####################################################################################################################
#####################################################################################################################
# Modification qualitative d'erreurs restantes constatées en explorant la base: Can be continued -------------------
#####################################################################################################################
#####################################################################################################################


eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1966) 74  65) 132"]<-"LANCASTER (1966) 74 132"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1966) AB 74"]<-"LANCASTER (1966) 74 132"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1971) AB 40"]<-"LANCASTER (1971) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1972) AB AB"]<-"LANCASTER (1971) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER , 1971. AB AB"]<-"LANCASTER (1971) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="LANCASTER (1980) 116 281"]<-"LANCASTER (1979) AB AB"        
eoeoe$identifiant[eoeoe$identifiant=="AKERLOF (1970) AB 89"]<-"AKERLOF (1970) 84 488"
eoeoe$identifiant[eoeoe$identifiant=="AKERLOF (1970) AB AB"]<-"AKERLOF (1970) 84 488"
eoeoe$identifiant[eoeoe$identifiant=="MUSSA (1978) AB AB"]<-"MUSSA (1978) 18 301"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (1985) AB AB"]<-"BAGWELL (1988) 19 59"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (2007) AB AB"]<-"BAGWELL (2007) 3 1701"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (1988) AB AB"]<-"BAGWELL (1991) 81 224"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL (1991) 81 . AB"]<-"BAGWELL (1991) 81 224"
eoeoe$identifiant[eoeoe$identifiant=="BAGWELL 1991 81 AB"]<-"BAGWELL (1991) 81 224"
eoeoe$identifiant[eoeoe$identifiant=="TIROLE (1990) AB AB"]<-"TIROLE (1988) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="TIROLE (1994) AB AB"]<-"TIROLE (1988) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="TIROLE (1998) AB AB"]<-"TIROLE (1988) AB AB"
eoeoe$identifiant[eoeoe$identifiant=="SPENCE (1973) AB AB"]<-"SPENCE (1973) 87 355"


# On calcule la fréquence de chaque identifiant

freq<-table(eoeoe$identifiant)
freq<-as.data.frame(freq)

# On stocke la fréquence comme nouvelle variable, ce qui nous servira à renseigner la taille des noeuds dans les graphes

eoeoe$frequence<-0
for(i in 1:nrow(eoeoe)){
  j<-which(eoeoe$identifiant[i] == freq$Var1)
  eoeoe$frequence[i]<-freq$Freq[j]
}





#################################################################################################################
#################################################################################################################
###### On fait la liste des auteurs les plus cités par décénnie --------------------------------------
#################################################################################################################
#################################################################################################################


load("Data_5_nodes.rda")



desco$Datepubli<-as.character(desco$Datepubli)
eoeoe$anneecitant<-0
for(i in 1:nrow(eoeoe)){
  j<-which(eoeoe$V2[i] == desco$Cartel)
  eoeoe$anneecitant[i] <- desco$Datepubli[j]
}


library(readr)
library(stringr)

eoeoe$anneecitant<-str_replace_all(string = eoeoe$anneecitant, pattern = "\\(", replacement = "")
eoeoe$anneecitant<-str_replace_all(string = eoeoe$anneecitant, pattern = "\\)", replacement = "")
eoeoe$anneecitant<-as.numeric(eoeoe$anneecitant)


freq19811990<-eoeoe[eoeoe$anneecitant==1980|eoeoe$anneecitant==1981|eoeoe$anneecitant==1982|eoeoe$anneecitant==1983|eoeoe$anneecitant==1984|eoeoe$anneecitant==1985|eoeoe$anneecitant==1986|eoeoe$anneecitant==1987|eoeoe$anneecitant==1988|eoeoe$anneecitant==1989,]
freq19912000<-eoeoe[eoeoe$anneecitant==1990|eoeoe$anneecitant==1991|eoeoe$anneecitant==1992|eoeoe$anneecitant==1993|eoeoe$anneecitant==1994|eoeoe$anneecitant==1995|eoeoe$anneecitant==1996|eoeoe$anneecitant==1997|eoeoe$anneecitant==1998|eoeoe$anneecitant==1999,]
freq20012010<-eoeoe[eoeoe$anneecitant==2000|eoeoe$anneecitant==2001|eoeoe$anneecitant==2002|eoeoe$anneecitant==2003|eoeoe$anneecitant==2004|eoeoe$anneecitant==2005|eoeoe$anneecitant==2006|eoeoe$anneecitant==2007|eoeoe$anneecitant==2008|eoeoe$anneecitant==2009,]
freq20112020<-eoeoe[eoeoe$anneecitant==2010|eoeoe$anneecitant==2011|eoeoe$anneecitant==2012|eoeoe$anneecitant==2013|eoeoe$anneecitant==2014|eoeoe$anneecitant==2015|eoeoe$anneecitant==2016|eoeoe$anneecitant==2017|eoeoe$anneecitant==2018|eoeoe$anneecitant==2019,]

freq19811990<-table(freq19811990$identifiant)
freq19811990<-as.data.frame(freq19811990)

freq19912000<-table(freq19912000$identifiant)
freq19912000<-as.data.frame(freq19912000)

freq20012010<-table(freq20012010$identifiant)
freq20012010<-as.data.frame(freq20012010)

freq20112020<-table(freq20112020$identifiant)
freq20112020<-as.data.frame(freq20112020)




top19811990<-freq19811990[rev(order(freq19811990$Freq)),]
top19912000<-freq19912000[rev(order(freq19912000$Freq)),]
top20012010<-freq20012010[rev(order(freq20012010$Freq)),]
top20112020<-freq20112020[rev(order(freq20112020$Freq)),]


top19811990<-top19811990[1:2000,]
top19912000<-top19912000[1:5000,]
top20012010<-top20012010[1:5000,]
top20112020<-top20112020[1:5000,]


####### On remplace les identifiants par la ref complète


for(i in 1:nrow(top19811990)){
  j<-which(top19811990$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top19811990$V1[i] <- eoeoe$V1[j[z]]
}

for(i in 1:nrow(top19912000)){
  j<-which(top19912000$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top19912000$V1[i] <- eoeoe$V1[j[z]]
}

for(i in 1:nrow(top20012010)){
  j<-which(top20012010$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top20012010$V1[i] <- eoeoe$V1[j[z]]
}

for(i in 1:nrow(top20112020)){
  j<-which(top20112020$Var1[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  top20112020$V1[i] <- eoeoe$V1[j[z]]
}



#### First

top19811990$authors<- str_extract_all(top19811990$V1, "(^.*\\, [[:alpha:]]\\.[[:alpha:]]\\.\\, )|(^.*\\, [[:alpha:]]\\.\\, )")
top19811990$authors<-as.character(top19811990$authors)
top19811990$authors2<- str_extract_all(top19811990$authors, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors)
top19811990$authors2<-as.character(top19811990$authors2)
top19811990$authors2<-str_replace(string = top19811990$authors2, pattern = "^\\.\\, ", replacement = "")
top19811990$authors3<- str_extract_all(top19811990$authors2, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors2<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors2)
top19811990$authors3<-as.character(top19811990$authors3)
top19811990$authors3<-str_replace(string = top19811990$authors3, pattern = "^\\.\\, ", replacement = "")
top19811990$authors4<- str_extract_all(top19811990$authors3, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors3<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors3)
top19811990$authors4<-as.character(top19811990$authors4)
top19811990$authors4<-str_replace(string = top19811990$authors4, pattern = "^\\.\\, ", replacement = "")
top19811990$authors5<- str_extract_all(top19811990$authors4, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors4<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors4)
top19811990$authors5<-as.character(top19811990$authors5)
top19811990$authors5<-str_replace(string = top19811990$authors5, pattern = "^\\.\\, ", replacement = "")
top19811990$authors6<- str_extract_all(top19811990$authors5, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors5<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors5)
top19811990$authors6<-as.character(top19811990$authors6)
top19811990$authors6<-str_replace(string = top19811990$authors6, pattern = "^\\.\\, ", replacement = "")
top19811990$authors7<- str_extract_all(top19811990$authors6, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors6<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors6)
top19811990$authors7<-as.character(top19811990$authors7)
top19811990$authors7<-str_replace(string = top19811990$authors7, pattern = "^\\.\\, ", replacement = "")
top19811990$authors8<- str_extract_all(top19811990$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors7<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors7)
top19811990$authors8<-as.character(top19811990$authors8)
top19811990$authors8<-str_replace(string = top19811990$authors8, pattern = "^\\.\\, ", replacement = "")
top19811990$authors9<- str_extract_all(top19811990$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top19811990$authors8<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19811990$authors8)
top19811990$authors9<-as.character(top19811990$authors9)
top19811990$authors9<-str_replace(string = top19811990$authors9, pattern = "^\\.\\, ", replacement = "")



top19811990$authors<-str_replace(string = top19811990$authors, pattern = "\\.\\, .*", replacement = "")
top19811990$authors2<-str_replace(string = top19811990$authors2, pattern = "\\.\\, .*", replacement = "")
top19811990$authors3<-str_replace(string = top19811990$authors3, pattern = "\\.\\, .*", replacement = "")
top19811990$authors4<-str_replace(string = top19811990$authors4, pattern = "\\.\\, .*", replacement = "")
top19811990$authors5<-str_replace(string = top19811990$authors5, pattern = "\\.\\, .*", replacement = "")
top19811990$authors6<-str_replace(string = top19811990$authors6, pattern = "\\.\\, .*", replacement = "")
top19811990$authors7<-str_replace(string = top19811990$authors7, pattern = "\\.\\, .*", replacement = "")
top19811990$authors8<-str_replace(string = top19811990$authors8, pattern = "\\.\\, .*", replacement = "")
top19811990$authors9<-str_replace(string = top19811990$authors9, pattern = "\\.\\, .*", replacement = "")


top19811990$authors[top19811990$authors == "character(0)"] <- "AB"
top19811990$authors2[top19811990$authors2 == "character(0)"] <- "AB"
top19811990$authors3[top19811990$authors3 == "character(0)"] <- "AB"
top19811990$authors4[top19811990$authors4 == "character(0)"] <- "AB"
top19811990$authors5[top19811990$authors5 == "character(0)"] <- "AB"
top19811990$authors6[top19811990$authors6 == "character(0)"] <- "AB"
top19811990$authors7[top19811990$authors7 == "character(0)"] <- "AB"
top19811990$authors8[top19811990$authors8 == "character(0)"] <- "AB"
top19811990$authors9[top19811990$authors9 == "character(0)"] <- "AB"


#### Second


top19912000$authors<- str_extract_all(top19912000$V1, "(^.*\\, [[:alpha:]]\\.[[:alpha:]]\\.\\, )|(^.*\\, [[:alpha:]]\\.\\, )")
top19912000$authors<-as.character(top19912000$authors)
top19912000$authors2<- str_extract_all(top19912000$authors, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors)
top19912000$authors2<-as.character(top19912000$authors2)
top19912000$authors2<-str_replace(string = top19912000$authors2, pattern = "^\\.\\, ", replacement = "")
top19912000$authors3<- str_extract_all(top19912000$authors2, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors2<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors2)
top19912000$authors3<-as.character(top19912000$authors3)
top19912000$authors3<-str_replace(string = top19912000$authors3, pattern = "^\\.\\, ", replacement = "")
top19912000$authors4<- str_extract_all(top19912000$authors3, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors3<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors3)
top19912000$authors4<-as.character(top19912000$authors4)
top19912000$authors4<-str_replace(string = top19912000$authors4, pattern = "^\\.\\, ", replacement = "")
top19912000$authors5<- str_extract_all(top19912000$authors4, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors4<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors4)
top19912000$authors5<-as.character(top19912000$authors5)
top19912000$authors5<-str_replace(string = top19912000$authors5, pattern = "^\\.\\, ", replacement = "")
top19912000$authors6<- str_extract_all(top19912000$authors5, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors5<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors5)
top19912000$authors6<-as.character(top19912000$authors6)
top19912000$authors6<-str_replace(string = top19912000$authors6, pattern = "^\\.\\, ", replacement = "")
top19912000$authors7<- str_extract_all(top19912000$authors6, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors6<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors6)
top19912000$authors7<-as.character(top19912000$authors7)
top19912000$authors7<-str_replace(string = top19912000$authors7, pattern = "^\\.\\, ", replacement = "")
top19912000$authors8<- str_extract_all(top19912000$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors7<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors7)
top19912000$authors8<-as.character(top19912000$authors8)
top19912000$authors8<-str_replace(string = top19912000$authors8, pattern = "^\\.\\, ", replacement = "")
top19912000$authors9<- str_extract_all(top19912000$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top19912000$authors8<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top19912000$authors8)
top19912000$authors9<-as.character(top19912000$authors9)
top19912000$authors9<-str_replace(string = top19912000$authors9, pattern = "^\\.\\, ", replacement = "")



top19912000$authors<-str_replace(string = top19912000$authors, pattern = "\\.\\, .*", replacement = "")
top19912000$authors2<-str_replace(string = top19912000$authors2, pattern = "\\.\\, .*", replacement = "")
top19912000$authors3<-str_replace(string = top19912000$authors3, pattern = "\\.\\, .*", replacement = "")
top19912000$authors4<-str_replace(string = top19912000$authors4, pattern = "\\.\\, .*", replacement = "")
top19912000$authors5<-str_replace(string = top19912000$authors5, pattern = "\\.\\, .*", replacement = "")
top19912000$authors6<-str_replace(string = top19912000$authors6, pattern = "\\.\\, .*", replacement = "")
top19912000$authors7<-str_replace(string = top19912000$authors7, pattern = "\\.\\, .*", replacement = "")
top19912000$authors8<-str_replace(string = top19912000$authors8, pattern = "\\.\\, .*", replacement = "")
top19912000$authors9<-str_replace(string = top19912000$authors9, pattern = "\\.\\, .*", replacement = "")


top19912000$authors[top19912000$authors == "character(0)"] <- "AB"
top19912000$authors2[top19912000$authors2 == "character(0)"] <- "AB"
top19912000$authors3[top19912000$authors3 == "character(0)"] <- "AB"
top19912000$authors4[top19912000$authors4 == "character(0)"] <- "AB"
top19912000$authors5[top19912000$authors5 == "character(0)"] <- "AB"
top19912000$authors6[top19912000$authors6 == "character(0)"] <- "AB"
top19912000$authors7[top19912000$authors7 == "character(0)"] <- "AB"
top19912000$authors8[top19912000$authors8 == "character(0)"] <- "AB"
top19912000$authors9[top19912000$authors9 == "character(0)"] <- "AB"


# Third


top20012010$authors<- str_extract_all(top20012010$V1, "(^.*\\, [[:alpha:]]\\.[[:alpha:]]\\.\\, )|(^.*\\, [[:alpha:]]\\.\\, )")
top20012010$authors<-as.character(top20012010$authors)
top20012010$authors2<- str_extract_all(top20012010$authors, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors)
top20012010$authors2<-as.character(top20012010$authors2)
top20012010$authors2<-str_replace(string = top20012010$authors2, pattern = "^\\.\\, ", replacement = "")
top20012010$authors3<- str_extract_all(top20012010$authors2, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors2<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors2)
top20012010$authors3<-as.character(top20012010$authors3)
top20012010$authors3<-str_replace(string = top20012010$authors3, pattern = "^\\.\\, ", replacement = "")
top20012010$authors4<- str_extract_all(top20012010$authors3, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors3<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors3)
top20012010$authors4<-as.character(top20012010$authors4)
top20012010$authors4<-str_replace(string = top20012010$authors4, pattern = "^\\.\\, ", replacement = "")
top20012010$authors5<- str_extract_all(top20012010$authors4, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors4<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors4)
top20012010$authors5<-as.character(top20012010$authors5)
top20012010$authors5<-str_replace(string = top20012010$authors5, pattern = "^\\.\\, ", replacement = "")
top20012010$authors6<- str_extract_all(top20012010$authors5, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors5<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors5)
top20012010$authors6<-as.character(top20012010$authors6)
top20012010$authors6<-str_replace(string = top20012010$authors6, pattern = "^\\.\\, ", replacement = "")
top20012010$authors7<- str_extract_all(top20012010$authors6, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors6<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors6)
top20012010$authors7<-as.character(top20012010$authors7)
top20012010$authors7<-str_replace(string = top20012010$authors7, pattern = "^\\.\\, ", replacement = "")
top20012010$authors8<- str_extract_all(top20012010$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors7<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors7)
top20012010$authors8<-as.character(top20012010$authors8)
top20012010$authors8<-str_replace(string = top20012010$authors8, pattern = "^\\.\\, ", replacement = "")
top20012010$authors9<- str_extract_all(top20012010$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top20012010$authors8<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20012010$authors8)
top20012010$authors9<-as.character(top20012010$authors9)
top20012010$authors9<-str_replace(string = top20012010$authors9, pattern = "^\\.\\, ", replacement = "")



top20012010$authors<-str_replace(string = top20012010$authors, pattern = "\\.\\, .*", replacement = "")
top20012010$authors2<-str_replace(string = top20012010$authors2, pattern = "\\.\\, .*", replacement = "")
top20012010$authors3<-str_replace(string = top20012010$authors3, pattern = "\\.\\, .*", replacement = "")
top20012010$authors4<-str_replace(string = top20012010$authors4, pattern = "\\.\\, .*", replacement = "")
top20012010$authors5<-str_replace(string = top20012010$authors5, pattern = "\\.\\, .*", replacement = "")
top20012010$authors6<-str_replace(string = top20012010$authors6, pattern = "\\.\\, .*", replacement = "")
top20012010$authors7<-str_replace(string = top20012010$authors7, pattern = "\\.\\, .*", replacement = "")
top20012010$authors8<-str_replace(string = top20012010$authors8, pattern = "\\.\\, .*", replacement = "")
top20012010$authors9<-str_replace(string = top20012010$authors9, pattern = "\\.\\, .*", replacement = "")


top20012010$authors[top20012010$authors == "character(0)"] <- "AB"
top20012010$authors2[top20012010$authors2 == "character(0)"] <- "AB"
top20012010$authors3[top20012010$authors3 == "character(0)"] <- "AB"
top20012010$authors4[top20012010$authors4 == "character(0)"] <- "AB"
top20012010$authors5[top20012010$authors5 == "character(0)"] <- "AB"
top20012010$authors6[top20012010$authors6 == "character(0)"] <- "AB"
top20012010$authors7[top20012010$authors7 == "character(0)"] <- "AB"
top20012010$authors8[top20012010$authors8 == "character(0)"] <- "AB"
top20012010$authors9[top20012010$authors9 == "character(0)"] <- "AB"

## Fourth



top20112020$authors<- str_extract_all(top20112020$V1, "(^.*\\, [[:alpha:]]\\.[[:alpha:]]\\.\\, )|(^.*\\, [[:alpha:]]\\.\\, )")
top20112020$authors<-as.character(top20112020$authors)
top20112020$authors2<- str_extract_all(top20112020$authors, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors)
top20112020$authors2<-as.character(top20112020$authors2)
top20112020$authors2<-str_replace(string = top20112020$authors2, pattern = "^\\.\\, ", replacement = "")
top20112020$authors3<- str_extract_all(top20112020$authors2, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors2<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors2)
top20112020$authors3<-as.character(top20112020$authors3)
top20112020$authors3<-str_replace(string = top20112020$authors3, pattern = "^\\.\\, ", replacement = "")
top20112020$authors4<- str_extract_all(top20112020$authors3, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors3<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors3)
top20112020$authors4<-as.character(top20112020$authors4)
top20112020$authors4<-str_replace(string = top20112020$authors4, pattern = "^\\.\\, ", replacement = "")
top20112020$authors5<- str_extract_all(top20112020$authors4, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors4<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors4)
top20112020$authors5<-as.character(top20112020$authors5)
top20112020$authors5<-str_replace(string = top20112020$authors5, pattern = "^\\.\\, ", replacement = "")
top20112020$authors6<- str_extract_all(top20112020$authors5, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors5<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors5)
top20112020$authors6<-as.character(top20112020$authors6)
top20112020$authors6<-str_replace(string = top20112020$authors6, pattern = "^\\.\\, ", replacement = "")
top20112020$authors7<- str_extract_all(top20112020$authors6, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors6<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors6)
top20112020$authors7<-as.character(top20112020$authors7)
top20112020$authors7<-str_replace(string = top20112020$authors7, pattern = "^\\.\\, ", replacement = "")
top20112020$authors8<- str_extract_all(top20112020$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors7<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors7)
top20112020$authors8<-as.character(top20112020$authors8)
top20112020$authors8<-str_replace(string = top20112020$authors8, pattern = "^\\.\\, ", replacement = "")
top20112020$authors9<- str_extract_all(top20112020$authors7, "\\.\\, [A-z].*\\, .*\\.\\,")
top20112020$authors8<-gsub("\\.\\, [A-z].*\\, .*\\.\\,", "",top20112020$authors8)
top20112020$authors9<-as.character(top20112020$authors9)
top20112020$authors9<-str_replace(string = top20112020$authors9, pattern = "^\\.\\, ", replacement = "")



top20112020$authors<-str_replace(string = top20112020$authors, pattern = "\\.\\, .*", replacement = "")
top20112020$authors2<-str_replace(string = top20112020$authors2, pattern = "\\.\\, .*", replacement = "")
top20112020$authors3<-str_replace(string = top20112020$authors3, pattern = "\\.\\, .*", replacement = "")
top20112020$authors4<-str_replace(string = top20112020$authors4, pattern = "\\.\\, .*", replacement = "")
top20112020$authors5<-str_replace(string = top20112020$authors5, pattern = "\\.\\, .*", replacement = "")
top20112020$authors6<-str_replace(string = top20112020$authors6, pattern = "\\.\\, .*", replacement = "")
top20112020$authors7<-str_replace(string = top20112020$authors7, pattern = "\\.\\, .*", replacement = "")
top20112020$authors8<-str_replace(string = top20112020$authors8, pattern = "\\.\\, .*", replacement = "")
top20112020$authors9<-str_replace(string = top20112020$authors9, pattern = "\\.\\, .*", replacement = "")


top20112020$authors[top20112020$authors == "character(0)"] <- "AB"
top20112020$authors2[top20112020$authors2 == "character(0)"] <- "AB"
top20112020$authors3[top20112020$authors3 == "character(0)"] <- "AB"
top20112020$authors4[top20112020$authors4 == "character(0)"] <- "AB"
top20112020$authors5[top20112020$authors5 == "character(0)"] <- "AB"
top20112020$authors6[top20112020$authors6 == "character(0)"] <- "AB"
top20112020$authors7[top20112020$authors7 == "character(0)"] <- "AB"
top20112020$authors8[top20112020$authors8 == "character(0)"] <- "AB"
top20112020$authors9[top20112020$authors9 == "character(0)"] <- "AB"



##### First


top19811990 <- na.omit(top19811990)

top19811990 <- top19811990[rep(row.names(top19811990), ifelse(top19811990$authors9!="AB",9,ifelse(top19811990$authors8!="AB",8,ifelse(top19811990$authors7!="AB",7,ifelse(top19811990$authors6!="AB",6,ifelse(top19811990$authors5!="AB",5,ifelse(top19811990$authors4!="AB",4,ifelse(top19811990$authors3!="AB",3,ifelse(top19811990$authors2!="AB",2,1))))))))),]



for(i in 1:(nrow(top19811990)-1)){if(top19811990[i,3]==top19811990[i+1,3]){
  top19811990[i+1,4]<-top19811990[i+1,5]
}else{top19811990[i+1,4]<-top19811990[i+1,4]}}


for(i in 1:(nrow(top19811990)-2)){if(top19811990[i,3]==top19811990[i+2,3]){
  top19811990[i+2,4]<-top19811990[i,6]
}else{top19811990[i+2,4]<-top19811990[i+2,4]}}

for(i in 1:(nrow(top19811990)-3)){if(top19811990[i,3]==top19811990[i+3,3]){
  top19811990[i+3,4]<-top19811990[i,7]
}else{top19811990[i+3,4]<-top19811990[i+3,4]}}


for(i in 1:(nrow(top19811990)-4)){if(top19811990[i,3]==top19811990[i+4,3]){
  top19811990[i+4,4]<-top19811990[i,8]
}else{top19811990[i+4,4]<-top19811990[i+4,4]}}


for(i in 1:(nrow(top19811990)-5)){if(top19811990[i,3]==top19811990[i+5,3]){
  top19811990[i+5,4]<-top19811990[i,9]
}else{top19811990[i+5,4]<-top19811990[i+5,4]}}


for(i in 1:(nrow(top19811990)-6)){if(top19811990[i,3]==top19811990[i+6,3]){
  top19811990[i+6,4]<-top19811990[i,10]
}else{top19811990[i+6,4]<-top19811990[i+6,4]}}



for(i in 1:(nrow(top19811990)-7)){if(top19811990[i,3]==top19811990[i+7,3]){
  top19811990[i+7,4]<-top19811990[i,11]
}else{top19811990[i+7,4]<-top19811990[i+7,4]}}


for(i in 1:(nrow(top19811990)-8)){if(top19811990[i,3]==top19811990[i+8,3]){
  top19811990[i+8,4]<-top19811990[i,12]
}else{top19811990[i+8,4]<-top19811990[i+8,4]}}



top19811990<-top19811990[,c(2,3,4)]



top19811990$authors<-str_replace(string = top19811990$authors, pattern = "\\,$", replacement = "")
top19811990$authors<-str_replace(string = top19811990$authors, pattern = "\\.$", replacement = "")

top19811990$authors<-iconv(top19811990$authors,from="UTF-8",to="ASCII//TRANSLIT")

##### On passe les noms en majuscule

top19811990$authors<-toupper(top19811990$authors)

top19811990$authors<-trimws(top19811990$authors)




###### Second



top19912000 <- na.omit(top19912000)

top19912000 <- top19912000[rep(row.names(top19912000), ifelse(top19912000$authors9!="AB",9,ifelse(top19912000$authors8!="AB",8,ifelse(top19912000$authors7!="AB",7,ifelse(top19912000$authors6!="AB",6,ifelse(top19912000$authors5!="AB",5,ifelse(top19912000$authors4!="AB",4,ifelse(top19912000$authors3!="AB",3,ifelse(top19912000$authors2!="AB",2,1))))))))),]



for(i in 1:(nrow(top19912000)-1)){if(top19912000[i,3]==top19912000[i+1,3]){
  top19912000[i+1,4]<-top19912000[i+1,5]
}else{top19912000[i+1,4]<-top19912000[i+1,4]}}


for(i in 1:(nrow(top19912000)-2)){if(top19912000[i,3]==top19912000[i+2,3]){
  top19912000[i+2,4]<-top19912000[i,6]
}else{top19912000[i+2,4]<-top19912000[i+2,4]}}

for(i in 1:(nrow(top19912000)-3)){if(top19912000[i,3]==top19912000[i+3,3]){
  top19912000[i+3,4]<-top19912000[i,7]
}else{top19912000[i+3,4]<-top19912000[i+3,4]}}


for(i in 1:(nrow(top19912000)-4)){if(top19912000[i,3]==top19912000[i+4,3]){
  top19912000[i+4,4]<-top19912000[i,8]
}else{top19912000[i+4,4]<-top19912000[i+4,4]}}


for(i in 1:(nrow(top19912000)-5)){if(top19912000[i,3]==top19912000[i+5,3]){
  top19912000[i+5,4]<-top19912000[i,9]
}else{top19912000[i+5,4]<-top19912000[i+5,4]}}


for(i in 1:(nrow(top19912000)-6)){if(top19912000[i,3]==top19912000[i+6,3]){
  top19912000[i+6,4]<-top19912000[i,10]
}else{top19912000[i+6,4]<-top19912000[i+6,4]}}



for(i in 1:(nrow(top19912000)-7)){if(top19912000[i,3]==top19912000[i+7,3]){
  top19912000[i+7,4]<-top19912000[i,11]
}else{top19912000[i+7,4]<-top19912000[i+7,4]}}


for(i in 1:(nrow(top19912000)-8)){if(top19912000[i,3]==top19912000[i+8,3]){
  top19912000[i+8,4]<-top19912000[i,12]
}else{top19912000[i+8,4]<-top19912000[i+8,4]}}



top19912000<-top19912000[,c(2,3,4)]



top19912000$authors<-str_replace(string = top19912000$authors, pattern = "\\,$", replacement = "")
top19912000$authors<-str_replace(string = top19912000$authors, pattern = "\\.$", replacement = "")

top19912000$authors<-iconv(top19912000$authors,from="UTF-8",to="ASCII//TRANSLIT")

##### On passe les noms en majuscule

top19912000$authors<-toupper(top19912000$authors)

top19912000$authors<-trimws(top19912000$authors)



###### Third


top20012010 <- na.omit(top20012010)

top20012010 <- top20012010[rep(row.names(top20012010), ifelse(top20012010$authors9!="AB",9,ifelse(top20012010$authors8!="AB",8,ifelse(top20012010$authors7!="AB",7,ifelse(top20012010$authors6!="AB",6,ifelse(top20012010$authors5!="AB",5,ifelse(top20012010$authors4!="AB",4,ifelse(top20012010$authors3!="AB",3,ifelse(top20012010$authors2!="AB",2,1))))))))),]



for(i in 1:(nrow(top20012010)-1)){if(top20012010[i,3]==top20012010[i+1,3]){
  top20012010[i+1,4]<-top20012010[i+1,5]
}else{top20012010[i+1,4]<-top20012010[i+1,4]}}


for(i in 1:(nrow(top20012010)-2)){if(top20012010[i,3]==top20012010[i+2,3]){
  top20012010[i+2,4]<-top20012010[i,6]
}else{top20012010[i+2,4]<-top20012010[i+2,4]}}

for(i in 1:(nrow(top20012010)-3)){if(top20012010[i,3]==top20012010[i+3,3]){
  top20012010[i+3,4]<-top20012010[i,7]
}else{top20012010[i+3,4]<-top20012010[i+3,4]}}


for(i in 1:(nrow(top20012010)-4)){if(top20012010[i,3]==top20012010[i+4,3]){
  top20012010[i+4,4]<-top20012010[i,8]
}else{top20012010[i+4,4]<-top20012010[i+4,4]}}


for(i in 1:(nrow(top20012010)-5)){if(top20012010[i,3]==top20012010[i+5,3]){
  top20012010[i+5,4]<-top20012010[i,9]
}else{top20012010[i+5,4]<-top20012010[i+5,4]}}


for(i in 1:(nrow(top20012010)-6)){if(top20012010[i,3]==top20012010[i+6,3]){
  top20012010[i+6,4]<-top20012010[i,10]
}else{top20012010[i+6,4]<-top20012010[i+6,4]}}



for(i in 1:(nrow(top20012010)-7)){if(top20012010[i,3]==top20012010[i+7,3]){
  top20012010[i+7,4]<-top20012010[i,11]
}else{top20012010[i+7,4]<-top20012010[i+7,4]}}


for(i in 1:(nrow(top20012010)-8)){if(top20012010[i,3]==top20012010[i+8,3]){
  top20012010[i+8,4]<-top20012010[i,12]
}else{top20012010[i+8,4]<-top20012010[i+8,4]}}



top20012010<-top20012010[,c(2,3,4)]



top20012010$authors<-str_replace(string = top20012010$authors, pattern = "\\,$", replacement = "")
top20012010$authors<-str_replace(string = top20012010$authors, pattern = "\\.$", replacement = "")

top20012010$authors<-iconv(top20012010$authors,from="UTF-8",to="ASCII//TRANSLIT")

##### On passe les noms en majuscule

top20012010$authors<-toupper(top20012010$authors)

top20012010$authors<-trimws(top20012010$authors)




###### Fourth




top20112020 <- na.omit(top20112020)

top20112020 <- top20112020[rep(row.names(top20112020), ifelse(top20112020$authors9!="AB",9,ifelse(top20112020$authors8!="AB",8,ifelse(top20112020$authors7!="AB",7,ifelse(top20112020$authors6!="AB",6,ifelse(top20112020$authors5!="AB",5,ifelse(top20112020$authors4!="AB",4,ifelse(top20112020$authors3!="AB",3,ifelse(top20112020$authors2!="AB",2,1))))))))),]



for(i in 1:(nrow(top20112020)-1)){if(top20112020[i,3]==top20112020[i+1,3]){
  top20112020[i+1,4]<-top20112020[i+1,5]
}else{top20112020[i+1,4]<-top20112020[i+1,4]}}


for(i in 1:(nrow(top20112020)-2)){if(top20112020[i,3]==top20112020[i+2,3]){
  top20112020[i+2,4]<-top20112020[i,6]
}else{top20112020[i+2,4]<-top20112020[i+2,4]}}

for(i in 1:(nrow(top20112020)-3)){if(top20112020[i,3]==top20112020[i+3,3]){
  top20112020[i+3,4]<-top20112020[i,7]
}else{top20112020[i+3,4]<-top20112020[i+3,4]}}


for(i in 1:(nrow(top20112020)-4)){if(top20112020[i,3]==top20112020[i+4,3]){
  top20112020[i+4,4]<-top20112020[i,8]
}else{top20112020[i+4,4]<-top20112020[i+4,4]}}


for(i in 1:(nrow(top20112020)-5)){if(top20112020[i,3]==top20112020[i+5,3]){
  top20112020[i+5,4]<-top20112020[i,9]
}else{top20112020[i+5,4]<-top20112020[i+5,4]}}


for(i in 1:(nrow(top20112020)-6)){if(top20112020[i,3]==top20112020[i+6,3]){
  top20112020[i+6,4]<-top20112020[i,10]
}else{top20112020[i+6,4]<-top20112020[i+6,4]}}



for(i in 1:(nrow(top20112020)-7)){if(top20112020[i,3]==top20112020[i+7,3]){
  top20112020[i+7,4]<-top20112020[i,11]
}else{top20112020[i+7,4]<-top20112020[i+7,4]}}


for(i in 1:(nrow(top20112020)-8)){if(top20112020[i,3]==top20112020[i+8,3]){
  top20112020[i+8,4]<-top20112020[i,12]
}else{top20112020[i+8,4]<-top20112020[i+8,4]}}



top20112020<-top20112020[,c(2,3,4)]



top20112020$authors<-str_replace(string = top20112020$authors, pattern = "\\,$", replacement = "")
top20112020$authors<-str_replace(string = top20112020$authors, pattern = "\\.$", replacement = "")

top20112020$authors<-iconv(top20112020$authors,from="UTF-8",to="ASCII//TRANSLIT")

##### On passe les noms en majuscule

top20112020$authors<-toupper(top20112020$authors)

top20112020$authors<-trimws(top20112020$authors)






freqauth119811990<-table(top19811990$authors)
freqauth119811990<-as.data.frame(freqauth119811990)

freqauth119912000<-table(top19912000$authors)
freqauth119912000<-as.data.frame(freqauth119912000)

freqauth120012010<-table(top20012010$authors)
freqauth120012010<-as.data.frame(freqauth120012010)

freqauth120112020<-table(top20112020$authors)
freqauth120112020<-as.data.frame(freqauth120112020)


library(questionr)



freqauth19811990<-wtd.table(x = top19811990$authors, weights = top19811990$Freq)
freqauth19811990<-as.data.frame(freqauth19811990)

freqauth19912000<-wtd.table(x = top19912000$authors, weights = top19912000$Freq)
freqauth19912000<-as.data.frame(freqauth19912000)

freqauth20012010<-wtd.table(x = top20012010$authors, weights = top20012010$Freq)
freqauth20012010<-as.data.frame(freqauth20012010)

freqauth20112020<-wtd.table(x = top20112020$authors, weights = top20112020$Freq)
freqauth20112020<-as.data.frame(freqauth20112020)




auth19811990<-merge(freqauth119811990,freqauth19811990, by="Var1")
auth19912000<-merge(freqauth119912000,freqauth19912000, by="Var1")
auth20012010<-merge(freqauth120012010,freqauth20012010, by="Var1")
auth20112020<-merge(freqauth120112020,freqauth20112020, by="Var1")



names(auth19811990)[names(auth19811990) == "Var1"] <- "Name"
names(auth19811990)[names(auth19811990) == "Freq.x"] <- "Number of Ocurrences"
names(auth19811990)[names(auth19811990) == "Freq.y"] <- "Items"


names(auth19912000)[names(auth19912000) == "Var1"] <- "Name"
names(auth19912000)[names(auth19912000) == "Freq.x"] <- "Number of Ocurrences"
names(auth19912000)[names(auth19912000) == "Freq.y"] <- "Items"


names(auth20012010)[names(auth20012010) == "Var1"] <- "Name"
names(auth20012010)[names(auth20012010) == "Freq.x"] <- "Number of Ocurrences"
names(auth20012010)[names(auth20012010) == "Freq.y"] <- "Items"


names(auth20112020)[names(auth20112020) == "Var1"] <- "Name"
names(auth20112020)[names(auth20112020) == "Freq.x"] <- "Number of Ocurrences"
names(auth20112020)[names(auth20112020) == "Freq.y"] <- "Items"



auth19811990<-auth19811990[rev(order(auth19811990$`Number of Ocurrences`)),]
auth19912000<-auth19912000[rev(order(auth19912000$`Number of Ocurrences`)),]
auth20012010<-auth20012010[rev(order(auth20012010$`Number of Ocurrences`)),]
auth20112020<-auth20112020[rev(order(auth20112020$`Number of Ocurrences`)),]


auth19811990$intrus<-auth19811990$Name=="AB"
auth19912000$intrus<-auth19912000$Name=="AB"
auth20012010$intrus<-auth20012010$Name=="AB"
auth20112020$intrus<-auth20112020$Name=="AB"



auth19811990<-auth19811990[auth19811990$intrus==F,]
auth19811990<-auth19811990[1:31,]
auth19811990<-auth19811990[,c(1:3)]


auth19912000<-auth19912000[auth19912000$intrus==F,]
auth19912000<-auth19912000[1:31,]
auth19912000<-auth19912000[,c(1:3)]


auth20012010<-auth20012010[auth20012010$intrus==F,]
auth20012010<-auth20012010[1:31,]
auth20012010<-auth20012010[,c(1:3)]


auth20112020<-auth20112020[auth20112020$intrus==F,]
auth20112020<-auth20112020[1:31,]
auth20112020<-auth20112020[,c(1:3)]


auth19811990$YEAR<-"1981-1990"
auth19912000$YEAR<-"1991-2000"
auth20012010$YEAR<-"2001-2010"
auth20112020$YEAR<-"2011-2020"


auth19811990$`Number of Ocurrences`<-1:nrow(auth19811990)
auth19912000$`Number of Ocurrences`<-1:nrow(auth19912000)
auth20012010$`Number of Ocurrences`<-1:nrow(auth20012010)
auth20112020$`Number of Ocurrences`<-1:nrow(auth20112020)


auth19811990<-auth19811990[,c(1)]
auth19912000<-auth19912000[,c(1)]
auth20012010<-auth20012010[,c(1)]
auth20112020<-auth20112020[,c(1)]



auth19811990<-as.data.frame(auth19811990)
auth19912000<-as.data.frame(auth19912000)
auth20012010<-as.data.frame(auth20012010)
auth20112020<-as.data.frame(auth20112020)


names(auth19811990)[names(auth19811990) == "auth19811990"] <- "1980-1989"
names(auth19912000)[names(auth19912000) == "auth19912000"] <- "1990-1999"
names(auth20012010)[names(auth20012010) == "auth20012010"] <- "2000-2009"
names(auth20112020)[names(auth20112020) == "auth20112020"] <- "2010-2019"


auth19811990$`1980-1989`<-as.character(auth19811990$`1980-1989`)
auth19912000$`1990-1999`<-as.character(auth19912000$`1990-1999`)
auth20012010$`2000-2009`<-as.character(auth20012010$`2000-2009`)
auth20112020$`2010-2019`<-as.character(auth20112020$`2010-2019`)



#for(i in 1:nrow(auth19811990)){
#  auth19811990$`1980-1989`[i]<-paste(i,"-",auth19811990$`1980-1989`[i])
#}

#for(i in 1:nrow(auth19912000)){
#  auth19912000$`1990-1999`[i]<-paste(i,"-",auth19912000$`1990-1999`[i])
#}

#for(i in 1:nrow(auth20012010)){
#  auth20012010$`2000-2009`[i]<-paste(i,"-",auth20012010$`2000-2009`[i])
#}


#for(i in 1:nrow(auth20112020)){
#  auth20112020$`2010-2019`[i]<-paste(i,"-",auth20112020$`2010-2019`[i])
#}

Rank<-1:nrow(auth19811990)

authy<-cbind(Rank,auth19811990,auth19912000,auth20012010,auth20112020)





library(knitr)
library(kableExtra)

authy %>%
  kbl() %>%
  kable_styling()



```




## 2.2- Bump Chart


```{r, message = FALSE}




auth19811990<-merge(freqauth119811990,freqauth19811990, by="Var1")
auth19912000<-merge(freqauth119912000,freqauth19912000, by="Var1")
auth20012010<-merge(freqauth120012010,freqauth20012010, by="Var1")
auth20112020<-merge(freqauth120112020,freqauth20112020, by="Var1")



names(auth19811990)[names(auth19811990) == "Var1"] <- "Name"
names(auth19811990)[names(auth19811990) == "Freq.x"] <- "Number of Ocurrences"
names(auth19811990)[names(auth19811990) == "Freq.y"] <- "Items"


names(auth19912000)[names(auth19912000) == "Var1"] <- "Name"
names(auth19912000)[names(auth19912000) == "Freq.x"] <- "Number of Ocurrences"
names(auth19912000)[names(auth19912000) == "Freq.y"] <- "Items"


names(auth20012010)[names(auth20012010) == "Var1"] <- "Name"
names(auth20012010)[names(auth20012010) == "Freq.x"] <- "Number of Ocurrences"
names(auth20012010)[names(auth20012010) == "Freq.y"] <- "Items"


names(auth20112020)[names(auth20112020) == "Var1"] <- "Name"
names(auth20112020)[names(auth20112020) == "Freq.x"] <- "Number of Ocurrences"
names(auth20112020)[names(auth20112020) == "Freq.y"] <- "Items"



auth19811990<-auth19811990[rev(order(auth19811990$`Number of Ocurrences`)),]
auth19912000<-auth19912000[rev(order(auth19912000$`Number of Ocurrences`)),]
auth20012010<-auth20012010[rev(order(auth20012010$`Number of Ocurrences`)),]
auth20112020<-auth20112020[rev(order(auth20112020$`Number of Ocurrences`)),]


auth19811990$intrus<-auth19811990$Name=="AB"
auth19912000$intrus<-auth19912000$Name=="AB"
auth20012010$intrus<-auth20012010$Name=="AB"
auth20112020$intrus<-auth20112020$Name=="AB"



auth19811990<-auth19811990[auth19811990$intrus==F,]
auth19811990<-auth19811990[1:31,]
auth19811990<-auth19811990[,c(1:3)]


auth19912000<-auth19912000[auth19912000$intrus==F,]
auth19912000<-auth19912000[1:31,]
auth19912000<-auth19912000[,c(1:3)]


auth20012010<-auth20012010[auth20012010$intrus==F,]
auth20012010<-auth20012010[1:31,]
auth20012010<-auth20012010[,c(1:3)]


auth20112020<-auth20112020[auth20112020$intrus==F,]
auth20112020<-auth20112020[1:31,]
auth20112020<-auth20112020[,c(1:3)]


auth19811990$YEAR<-"1981-1990"
auth19912000$YEAR<-"1991-2000"
auth20012010$YEAR<-"2001-2010"
auth20112020$YEAR<-"2011-2020"


auth19811990$`Number of Ocurrences`<-1:nrow(auth19811990)
auth19912000$`Number of Ocurrences`<-1:nrow(auth19912000)
auth20012010$`Number of Ocurrences`<-1:nrow(auth20012010)
auth20112020$`Number of Ocurrences`<-1:nrow(auth20112020)


auth<-rbind(auth19811990,auth19912000,auth20012010,auth20112020)


library(ggplot2)
library(dplyr)






my_theme <- function() {
  
  # Colors
  color.background = "white"
  color.text = "#22211d"
  
  # Begin construction of chart
  theme_bw(base_size=15) +
    
    # Format background colors
    theme(panel.background = element_rect(fill=color.background,
                                          color=color.background)) +
    theme(plot.background  = element_rect(fill=color.background,
                                          color=color.background)) +
    theme(panel.border     = element_rect(color=color.background)) +
    theme(strip.background = element_rect(fill=color.background,
                                          color=color.background)) +
    
    # Format the grid
    theme(panel.grid.major.y = element_blank()) +
    theme(panel.grid.minor.y = element_blank()) +
    theme(axis.ticks       = element_blank()) +
    
    # Format the legend
    theme(legend.position = "none") +
    
    # Format title and axis labels
    theme(plot.title       = element_text(color=color.text, size=5, face = "bold")) +
    theme(axis.title.x     = element_text(size=0, color="black", face = "bold")) +
    theme(axis.title.y     = element_text(size=0, color="black", face = "bold",
                                          vjust=1.25)) +
    theme(axis.text.x      = element_text(size=0, vjust=0.5, hjust=0.5,
                                          color = color.text)) +
    ### Taille des nombre
    theme(axis.text.y      = element_text(size=2.5, color = color.text)) +
    theme(strip.text       = element_text(face = "bold")) +
    
    # Plot margins
    # Contour du graphique
    theme(plot.margin = unit(c(0, 0.2, 0.3, 0), "cm"))
}




library(ggiraph)



gg_point=ggplot(auth,aes(x = as.factor(YEAR), y = `Number of Ocurrences`, group = Name)) +
  # Taille des lignes
  geom_line_interactive(aes(color = Name, alpha = 1,tooltip=Name, data_id = Name), size = 0.3) +
  # Taille des points
  geom_point_interactive(aes(x = as.factor(YEAR), y = `Number of Ocurrences`, group = Name, color = Name, alpha = 1,tooltip = Name, data_id = Name), size = 1) +
  geom_point_interactive(color = "#FFFFFF", size = 0.01) +
  scale_y_reverse(breaks = 1:table(auth$YEAR)[[1]]) + 
  scale_x_discrete(breaks = 1:length(table(auth$YEAR))) +
  theme(legend.position = 'none') +
  # le x designe le positionnement des auteurs à gauche
  geom_text(data = auth %>% filter(YEAR == "1981-1990"),
            aes(label = Name, x = 0.42) , hjust = 0.0,
            fontface = "bold", color = "#888888", size = 0.7) +
  # idem mais à droite
  geom_text(data = auth %>% filter(YEAR == "2011-2020"),
            aes(label = Name, x = 4.5) , hjust = 1.0,
            fontface = "bold", color = "#888888", size = 0.7) +
  labs(x = '', y = '', title = 'Most quoted authors (1980-1989, 1990-1999, 2000-2009, 2010-2019)') +
  my_theme() 




girafe(ggobj = gg_point, width_svg = 3, height_svg = 2,
       options = list(
         opts_hover_inv(css = "opacity:0.1;"),
         opts_hover(css = "stroke-width:2;")
       ))






```


# 3- Bibliographic coupling 2010-2019


```{r fig.asp = 0.8, fig.height=5, fig.width = 7, out.width = "100%", message = FALSE, warning=FALSE, fig.align = "center"}


##### On a une colonne d'identifiant unique des articles et une colonne avec les refs biblios
##### recodées, on peut donc soumettre ça au package d'Aurelien

set.seed(12)


setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")

load("Data_5_nodes.rda")
load("Data_7_finalbase.rda")

library(readr)
library(stringr)
#library(bibliometrix)
library(tidyverse)
library(biblionetwork)
#library(devtools)
#devtools::install_github("agoutsmedt/biblionetwork")


eoeoe2<-eoeoe

simple<-unique(eoeoe2$V2)
simple<-as.data.frame(simple)

#setdiff(desco$Cartel,simple[,1])

desco<-desco[desco$Cartel!=108237,]


comp<-cbind(simple,desco$Cartel)




desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2010|2011|2012|2013|2014|2015|2016|2017|2018|2019")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1970|1971|1972|1973|1974|1975|1976|1977|1978|1979|1980|1981|1982|1983|1984|1985|1986|1987|1988|1989|1990|1991|1992|1993|1994|1995|1996|1997|1998|1990|2000")

desco<-desco[desco$sloubi==T,]


Cartel<-desco$Cartel

eoeoe2$toofar<-"AB"
for(i in 1:nrow(eoeoe2)){
  if(eoeoe2$V2[i]%in%Cartel){eoeoe2$toofar[i]<-T}else{eoeoe2$toofar[i]<-F}}

eoeoe2<-eoeoe2[eoeoe2$toofar==T,]

Carlito<-unique(eoeoe2$V2)

Carlito<-as.data.frame(Carlito)
Cartel<-as.data.frame(Cartel)


Cabal<-cbind(Carlito,Cartel)


eoeoe2$V2<-as.character(eoeoe2$V2)
eoeoe2$identifiant<-as.character(eoeoe2$identifiant)
desco$Cartel<-as.character(desco$Cartel)



Basefinale<-biblio_coupling(eoeoe2, source = "V2", ref = "identifiant", normalized_weight_only = FALSE, weight_threshold = 2)



#devtools::install_github("agoutsmedt/networkflow")

library(biblionetwork)
library(magrittr)
library(dplyr)
library(tidygraph)
library(networkflow)
library(tidygraph)
#devtools::install_github("ParkerICI/vite")
library(vite)




Edges_coupling2<-Basefinale[,-c(4)]


Nodes_coupling2<-desco

Nodes_coupling2$frequence<-1

Nodes_coupling2$Datepubli<-as.character(Nodes_coupling2$Datepubli)

Nodes_coupling2$author_date<-paste(Nodes_coupling2$Cartel,Nodes_coupling2$Firstauthor,Nodes_coupling2$Datepubli)

palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

graph <- tbl_main_component(nodes = Nodes_coupling2, edges = Edges_coupling2, directed = FALSE, node_key = "Cartel", nb_components = 1)

graph <- leiden_workflow(graph, res_1 = 1)

graph <- community_colors(graph, palette, community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree())



graph <- community_names(graph, ordering_column = "degree", naming = "author_date", community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>% 
  mutate(size = degree) # use here what you will use for the size of the nodes in the graph. Force Atlas will take care of avoiding overlapping

graph <- vite::complete_forceatlas2(graph, first.iter = 10000, overlap.method = "repel", overlap.iter = 1000)



graph123<-as.data.frame(graph)



#################################################################################################################
#################################################################################################################
# On extrait les abstracts pour faire de l'analyse textuelle ---------------------------------
#################################################################################################################
#################################################################################################################


load("Data_4_Abstracts.rda")



zalerit$comcitant<-0
for(i in 1:nrow(graph123)){
  j<-which(zalerit$Cartel == graph123$Id[i])
  zalerit$comcitant[j]<-graph123$Com_ID[i]
}


library(dplyr)
library(janeaustenr) #Inutile je pense
library(tidytext)
library(gutenbergr)  #Idem
library(pdftools)
library(tidyverse)
library(qdapRegex)


zaler2<-zalerit[,c(1,3)]

zaler2<-zaler2[zaler2$comcitant!=0,]

zaler2$V1<-as.character(zaler2$V1)
zaler2$comcitant<-as.character(zaler2$comcitant)



paly<-length(table(zaler2$comcitant))


Basetotale_words <- zaler2 %>%
  unnest_tokens(word, V1) %>%
  count(comcitant, word, sort = TRUE)



# On supprime les mots de deux lettres et de une lettre
Basetotale_words$word<-rm_nchar_words(Basetotale_words$word, 2)
Basetotale_words$word<-rm_nchar_words(Basetotale_words$word, 1)


# On remplace le vide que cree l'etape precedente par des NA et on supprime les NA
Basetotale_words$word[Basetotale_words$word==""] <- NA
Basetotale_words <- na.omit(Basetotale_words)


mystopwords <- tibble(word = c("qmi","consumerswho"))


Basetotale_words <- anti_join(Basetotale_words, mystopwords,
                              by = "word")


plot_Basetotale <- Basetotale_words %>%
  bind_tf_idf(word, comcitant, n) %>%
  mutate(word = str_remove_all(word, "_")) %>%
  group_by(comcitant) %>%
  slice_max(tf_idf, n = 25) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, comcitant)) %>%
  mutate(comcitant = factor(comcitant))



palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

palette <- palette[1:paly]

#ggplot(plot_Basetotale, aes(word, tf_idf, fill = comcitant)) +
#  geom_col(show.legend = FALSE) +
#  labs(x = NULL, y = "tf-idf") +
#  facet_wrap(~comcitant, ncol = 2, scales = "free") +
#  coord_flip() +
#  scale_x_reordered() +
#  scale_fill_manual(values=c(palette))


plot_Basetotale2<-plot_Basetotale[,c(1,2)]


plot_Basetotale2$word<-str_replace(string = plot_Basetotale2$word, pattern = "___.*", replacement = "")


plot_Basetotale2$word<-toupper(plot_Basetotale2$word)

plot_Basetotale2$word<-trimws(plot_Basetotale2$word)


plot_Basetotale2$plural <- gsub('.{1}$','', plot_Basetotale2$word)


j<-unique(plot_Basetotale2$comcitant)

plot_Basetotale2$dede <- 0
for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])
  for(m in k){if(any(plot_Basetotale2$plural[m]==plot_Basetotale2$word[k])){
    z<-which(plot_Basetotale2$plural[m]==plot_Basetotale2$word[k])
    if(k[z]<m){
      plot_Basetotale2$dede[k[z]]<-10
      plot_Basetotale2$dede[m]<-28}else{
        plot_Basetotale2$dede[k[z]]<-28
        plot_Basetotale2$dede[m]<-10}
  }else{
    plot_Basetotale2$dede[m]<-plot_Basetotale2$dede[m]}}
}



plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$dede!=28,]
plot_Basetotale2<-plot_Basetotale2[,c(1,2)]



j<-unique(plot_Basetotale2$comcitant)
plot_Basetotale2$comp<-0

for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])[1:4]
  plot_Basetotale2$comp[k]<-1
}

plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$comp==T,]





for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])[1]
  plot_Basetotale2$comp[k]<-paste(plot_Basetotale2$word[k],";",plot_Basetotale2$word[k+1],";",plot_Basetotale2$word[k+2],";",plot_Basetotale2$word[k+3])
}


plot_Basetotale2<-plot_Basetotale2[,c(1,3)]
plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$comp!=1,]



names(plot_Basetotale2)[names(plot_Basetotale2) == "comcitant"] <- "Com_ID"


#################################################################################################################################
#################################################################################################################################
# Fin de l'extraction des mots-clés --------------------------------------------------------------
#################################################################################################################################
#################################################################################################################################



top_nodes  <- top_nodes(graph, ordering_column = "degree", top_n = 10, top_n_per_com = 1)


community_labels <- community_labels(graph, community_name_column = "Community_name", community_size_column = "Size_com")

community_labels$identifiant<-str_sub (community_labels$Community_name, 1,2)

for(i in 1:nrow(community_labels)){
  j<-which(community_labels$identifiant[i] == plot_Basetotale2)
  community_labels$Community_name[i]<- plot_Basetotale2$comp[j]
}





library(ggraph)
library(ggrepel) 
library(ggnewscale)



ggraph(graph, "manual", x = x, y = y) + 
  geom_edge_arc(aes(color = color_edges, width = weight), alpha = 0.4, strength = 0.2, show.legend = FALSE) +
  scale_edge_width_continuous(range = c(0.1,2)) +
  scale_edge_colour_identity() +
  geom_node_point(aes(x=x, y=y, size = degree, fill = color), pch = 21, alpha = 0.9, show.legend = FALSE) +
  scale_size_continuous(range = c(0.2,13)) +
  scale_fill_identity() +
  new_scale("size") +
  geom_text_repel(data=top_nodes, aes(x=x, y=y, label = Label), size = 2, fontface="bold", alpha = 1, point.padding=NA, show.legend = FALSE) +
  geom_label_repel(data=community_labels, aes(x=x, y=y, label = Community_name, fill = color, size = Size_com), fontface="bold", alpha = 0.9, point.padding=NA, show.legend = FALSE) +
  scale_size_continuous(range = c(0.5,5)) +
  theme_void()





```



# 4- Co-citation 2010-2019

```{r fig.asp = 0.8, fig.height=5, fig.width = 7, out.width = "100%", message = FALSE, warning=FALSE, fig.align = "center"}

##### On a une colonne d'identifiant unique des articles et une colonne avec les refs biblios
##### recodées, on peut donc soumettre ça au package d'Aurelien

set.seed(16)


setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")


load("Data_5_nodes.rda")
load("Data_7_finalbase.rda")




library(readr)
library(stringr)
#library(bibliometrix)
library(tidyverse)
library(biblionetwork)
#library(devtools)
#devtools::install_github("agoutsmedt/biblionetwork")


eoeoe2<-eoeoe

simple<-unique(eoeoe2$V2)
simple<-as.data.frame(simple)

#setdiff(desco$Cartel,simple[,1])

desco<-desco[desco$Cartel!=108237,]




comp<-cbind(simple,desco$Cartel)




desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2010|2011|2012|2013|2014|2015|2016|2017|2018|2019")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1970|1971|1972|1973|1974|1975|1976|1977|1978|1979")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1980|1981|1982|1983|1984|1985|1986|1987|1988|1989")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1990|1991|1992|1993|1994|1995|1996|1997|1998|1999")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2000|2001|2002|2003|2004|2005|2006|2007|2008|2009")



desco<-desco[desco$sloubi==T,]


Cartel<-desco$Cartel

eoeoe2$toofar<-"AB"
for(i in 1:nrow(eoeoe2)){
  if(eoeoe2$V2[i]%in%Cartel){eoeoe2$toofar[i]<-T}else{eoeoe2$toofar[i]<-F}}

eoeoe2<-eoeoe2[eoeoe2$toofar==T,]

Carlito<-unique(eoeoe2$V2)

Carlito<-as.data.frame(Carlito)
Cartel<-as.data.frame(Cartel)


Cabal<-cbind(Carlito,Cartel)


eoeoe2$V2<-as.character(eoeoe2$V2)
eoeoe2$identifiant<-as.character(eoeoe2$identifiant)
desco$Cartel<-as.character(desco$Cartel)


Basefinale<-biblio_coupling(eoeoe2, source = "identifiant", ref = "V2", normalized_weight_only = FALSE, weight_threshold = 2)



#devtools::install_github("agoutsmedt/networkflow")

library(biblionetwork)
library(magrittr)
library(dplyr)
library(tidygraph)
library(networkflow)
#devtools::install_github("agoutsmedt/networkflow")

library(tidygraph)
#devtools::install_github("ParkerICI/vite")
library(vite)


Edges_coupling2<-Basefinale[,-c(4)]


Nodes_coupling2<-unique(eoeoe2$identifiant)

Nodes_coupling2<-as.data.frame(Nodes_coupling2)

Nodes_coupling2$frequence<-0
for(i in 1:nrow(Nodes_coupling2)){
  j<-which(Nodes_coupling2$Nodes_coupling2[i] == eoeoe2$identifiant)[1]
  Nodes_coupling2$frequence[i]<-eoeoe2$frequence[j]
}


Nodes_coupling2$ids<-Nodes_coupling2$Nodes_coupling2


palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

graph <- tbl_main_component(nodes = Nodes_coupling2, edges = Edges_coupling2, directed = FALSE, node_key = "Cartel", nb_components = 1)


## Varying the resolution of the algorithm results in a different partition and 
## different number of communities. A lower resolution means less communities, and conversely.
## The basic resolution of the leiden_workflow() is set by res_1 and equals 1 by default. 
## You can vary this parameter, but also try a second resolution with res_2 and a third one 
## with res_3
## On peut l'enlever avec un argument par défaut de 1


graph <- leiden_workflow(graph, res_1 = 0.5)

graph <- community_colors(graph, palette, community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree())



graph <- community_names(graph, ordering_column = "degree", naming = "ids", community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>% 
  mutate(size = frequence) # use here what you will use for the size of the nodes in the graph. Force Atlas will take care of avoiding overlapping


######## First.iter initiallement 5000, j'ai baissé pour arriver à le faire tourner


graph <- vite::complete_forceatlas2(graph, first.iter = 10000, overlap.method = "repel", overlap.iter = 1500)


top_nodes  <- top_nodes(graph, ordering_column = "degree", top_n = 10, top_n_per_com = 1)


community_labels2 <- community_labels(graph, community_name_column = "Community_name", community_size_column = "Size_com")


library(ggraph)
library(ggrepel) 
library(ggnewscale)


graph456<-as.data.frame(graph)




ggraph(graph, "manual", x = x, y = y) + 
  geom_edge_arc(aes(color = color_edges, width = weight), alpha = 0.4, strength = 0.2, show.legend = FALSE) +
  scale_edge_width_continuous(range = c(0.1,2)) +
  scale_edge_colour_identity() +
  geom_node_point(aes(x=x, y=y, size = degree, fill = color), pch = 21, alpha = 0.9, show.legend = FALSE) +
  scale_size_continuous(range = c(0.2,13)) +
  scale_fill_identity() +
  new_scale("size") +
  geom_text_repel(data=top_nodes, aes(x=x, y=y, label = Label), size = 2, fontface="bold", alpha = 1, point.padding=NA, show.legend = FALSE) +
  geom_label_repel(data=community_labels2, aes(x=x, y=y, label = Community_name, fill = color, size = Size_com), fontface="bold", alpha = 0.9, point.padding=NA, show.legend = FALSE) +
  scale_size_continuous(range = c(0.5,5)) +
  theme_void()





```


```{r}


graph123<-graph123[,c(1,9)]
graph456<-graph456[,c(1,4)]



eoeoe$comcitant<-0
for(i in 1:nrow(graph123)){
  j<-which(eoeoe$V2 == graph123$Id[i])
  eoeoe$comcitant[j]<-graph123$Com_ID[i]
}


eoeoe$comcite<-0
for(i in 1:nrow(graph456)){
  j<-which(eoeoe$identifiant == graph456$Id[i])
  eoeoe$comcite[j]<-graph456$Com_ID[i]
}



eoeoe4<-eoeoe
eoeoe4<-eoeoe4[eoeoe4$comcitant!=0,]
eoeoe4<-eoeoe4[eoeoe4$comcite!=0,]


community_labels2$ID<-gsub("-.*", "",community_labels2$Community_name)

community_labels2$IDil<-gsub(".*-", "",community_labels2$Community_name)


community_labels2$IDcompl<-"AB"
for(i in 1:nrow(community_labels2)){
  j<-which(community_labels2$IDil[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  community_labels2$IDcompl[i] <- eoeoe$V1[j[z]]
}


tableau<-as.data.frame.matrix(prop.table(table(eoeoe4$comcitant,eoeoe4$comcite),margin=1)*100)
library(dplyr)
tableau<-tableau %>% mutate_if(is.numeric, ~round(., 1))


community_labels<-community_labels[order(community_labels$identifiant),]
row.names(tableau) <- community_labels$Community_name

community_labels2<-community_labels2[order(community_labels2$Community_name),]
colnames(tableau)<- community_labels2$ID


for(i in 1:nrow(community_labels2)){
  community_labels2$IDcompl[i]<-paste(i,"-",community_labels2$IDcompl[i])
}

Legend<-community_labels2[,c(8)]

Legend<-as.data.frame(Legend)

names(Legend)[names(Legend) == "IDcompl"] <- "Complete reference of the clusters"

library(knitr)
library(kableExtra)


kable(Legend)



```

# 5- Connect the communities 2010-2019


```{r}


########################################################################################
##############################################################################################################
# Connecter les communautés -----------------------------
##############################################################################################################
##############################################################################################################


tableau %>%
  kbl() %>%
  kable_styling()


```






# 6- Bibliographic coupling 2000-2009

```{r fig.asp = 0.8, fig.height=5, fig.width = 7, out.width = "100%", message = FALSE, warning=FALSE, fig.align = "center"}




#####################################################################################################################
#####################################################################################################################
# Coupling Co-citation 2000-2009 -------------------
#####################################################################################################################
#####################################################################################################################




#####################################################################################################################
#####################################################################################################################
# Bibliographic Coupling 2000-2009----------------------------------------------------
#####################################################################################################################
#####################################################################################################################


##### On a une colonne d'identifiant unique des articles et une colonne avec les refs biblios
##### recodées, on peut donc soumettre ça au package d'Aurelien

set.seed(12)

setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")

load("Data_5_nodes.rda")
load("Data_7_finalbase.rda")


library(readr)
library(stringr)
#library(bibliometrix)
library(tidyverse)
library(biblionetwork)
#library(devtools)
#devtools::install_github("agoutsmedt/biblionetwork")


eoeoe2<-eoeoe

simple<-unique(eoeoe2$V2)
simple<-as.data.frame(simple)

#setdiff(desco$Cartel,simple[,1])

desco<-desco[desco$Cartel!=108237,]


comp<-cbind(simple,desco$Cartel)




desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2000|2001|2002|2003|2004|2005|2006|2007|2008|2009")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1970|1971|1972|1973|1974|1975|1976|1977|1978|1979|1980|1981|1982|1983|1984|1985|1986|1987|1988|1989|1990|1991|1992|1993|1994|1995|1996|1997|1998|1990|2000")

desco<-desco[desco$sloubi==T,]


Cartel<-desco$Cartel

eoeoe2$toofar<-"AB"
for(i in 1:nrow(eoeoe2)){
  if(eoeoe2$V2[i]%in%Cartel){eoeoe2$toofar[i]<-T}else{eoeoe2$toofar[i]<-F}}

eoeoe2<-eoeoe2[eoeoe2$toofar==T,]

Carlito<-unique(eoeoe2$V2)

Carlito<-as.data.frame(Carlito)
Cartel<-as.data.frame(Cartel)


Cabal<-cbind(Carlito,Cartel)


eoeoe2$V2<-as.character(eoeoe2$V2)
eoeoe2$identifiant<-as.character(eoeoe2$identifiant)
desco$Cartel<-as.character(desco$Cartel)



Basefinale<-biblio_coupling(eoeoe2, source = "V2", ref = "identifiant", normalized_weight_only = FALSE, weight_threshold = 2)



#devtools::install_github("agoutsmedt/networkflow")

library(biblionetwork)
library(magrittr)
library(dplyr)
library(tidygraph)
library(networkflow)
library(tidygraph)
#devtools::install_github("ParkerICI/vite")
library(vite)




Edges_coupling2<-Basefinale[,-c(4)]


Nodes_coupling2<-desco

Nodes_coupling2$frequence<-1

Nodes_coupling2$Datepubli<-as.character(Nodes_coupling2$Datepubli)

Nodes_coupling2$author_date<-paste(Nodes_coupling2$Cartel,Nodes_coupling2$Firstauthor,Nodes_coupling2$Datepubli)

palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

graph <- tbl_main_component(nodes = Nodes_coupling2, edges = Edges_coupling2, directed = FALSE, node_key = "Cartel", nb_components = 1)

graph <- leiden_workflow(graph, res_1 = 1)

graph <- community_colors(graph, palette, community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree())



graph <- community_names(graph, ordering_column = "degree", naming = "author_date", community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>% 
  mutate(size = degree) # use here what you will use for the size of the nodes in the graph. Force Atlas will take care of avoiding overlapping

graph <- vite::complete_forceatlas2(graph, first.iter = 10000, overlap.method = "repel", overlap.iter = 1000)



graph123<-as.data.frame(graph)



#################################################################################################################
#################################################################################################################
# On extrait les abstracts pour faire de l'analyse textuelle ---------------------------------
#################################################################################################################
#################################################################################################################


load("Data_4_Abstracts.rda")


zalerit$comcitant<-0
for(i in 1:nrow(graph123)){
  j<-which(zalerit$Cartel == graph123$Id[i])
  zalerit$comcitant[j]<-graph123$Com_ID[i]
}


library(dplyr)
library(janeaustenr) #Inutile je pense
library(tidytext)
library(gutenbergr)  #Idem
library(pdftools)
library(tidyverse)
library(qdapRegex)


zaler2<-zalerit[,c(1,3)]

zaler2<-zaler2[zaler2$comcitant!=0,]

zaler2$V1<-as.character(zaler2$V1)
zaler2$comcitant<-as.character(zaler2$comcitant)



paly<-length(table(zaler2$comcitant))


Basetotale_words <- zaler2 %>%
  unnest_tokens(word, V1) %>%
  count(comcitant, word, sort = TRUE)



# On supprime les mots de deux lettres et de une lettre
Basetotale_words$word<-rm_nchar_words(Basetotale_words$word, 2)
Basetotale_words$word<-rm_nchar_words(Basetotale_words$word, 1)


# On remplace le vide que cree l'etape precedente par des NA et on supprime les NA
Basetotale_words$word[Basetotale_words$word==""] <- NA
Basetotale_words <- na.omit(Basetotale_words)


mystopwords <- tibble(word = c("qmi","consumerswho"))


Basetotale_words <- anti_join(Basetotale_words, mystopwords,
                              by = "word")


plot_Basetotale <- Basetotale_words %>%
  bind_tf_idf(word, comcitant, n) %>%
  mutate(word = str_remove_all(word, "_")) %>%
  group_by(comcitant) %>%
  slice_max(tf_idf, n = 25) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, comcitant)) %>%
  mutate(comcitant = factor(comcitant))



palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

palette <- palette[1:paly]

#ggplot(plot_Basetotale, aes(word, tf_idf, fill = comcitant)) +
#  geom_col(show.legend = FALSE) +
#  labs(x = NULL, y = "tf-idf") +
#  facet_wrap(~comcitant, ncol = 2, scales = "free") +
#  coord_flip() +
#  scale_x_reordered() +
#  scale_fill_manual(values=c(palette))


plot_Basetotale2<-plot_Basetotale[,c(1,2)]


plot_Basetotale2$word<-str_replace(string = plot_Basetotale2$word, pattern = "___.*", replacement = "")


plot_Basetotale2$word<-toupper(plot_Basetotale2$word)

plot_Basetotale2$word<-trimws(plot_Basetotale2$word)


plot_Basetotale2$plural <- gsub('.{1}$','', plot_Basetotale2$word)


j<-unique(plot_Basetotale2$comcitant)

plot_Basetotale2$dede <- 0
for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])
  for(m in k){if(any(plot_Basetotale2$plural[m]==plot_Basetotale2$word[k])){
    z<-which(plot_Basetotale2$plural[m]==plot_Basetotale2$word[k])
    if(k[z]<m){
      plot_Basetotale2$dede[k[z]]<-10
      plot_Basetotale2$dede[m]<-28}else{
        plot_Basetotale2$dede[k[z]]<-28
        plot_Basetotale2$dede[m]<-10}
  }else{
    plot_Basetotale2$dede[m]<-plot_Basetotale2$dede[m]}}
}



plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$dede!=28,]
plot_Basetotale2<-plot_Basetotale2[,c(1,2)]



j<-unique(plot_Basetotale2$comcitant)
plot_Basetotale2$comp<-0

for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])[1:4]
  plot_Basetotale2$comp[k]<-1
}

plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$comp==T,]





for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])[1]
  plot_Basetotale2$comp[k]<-paste(plot_Basetotale2$word[k],";",plot_Basetotale2$word[k+1],";",plot_Basetotale2$word[k+2],";",plot_Basetotale2$word[k+3])
}


plot_Basetotale2<-plot_Basetotale2[,c(1,3)]
plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$comp!=1,]



names(plot_Basetotale2)[names(plot_Basetotale2) == "comcitant"] <- "Com_ID"


#################################################################################################################################
#################################################################################################################################
# Fin de l'extraction des mots-clés --------------------------------------------------------------
#################################################################################################################################
#################################################################################################################################



top_nodes  <- top_nodes(graph, ordering_column = "degree", top_n = 10, top_n_per_com = 1)


community_labels <- community_labels(graph, community_name_column = "Community_name", community_size_column = "Size_com")

community_labels$identifiant<-str_sub (community_labels$Community_name, 1,2)

for(i in 1:nrow(community_labels)){
  j<-which(community_labels$identifiant[i] == plot_Basetotale2)
  community_labels$Community_name[i]<- plot_Basetotale2$comp[j]
}



library(ggraph)
library(ggrepel) 
library(ggnewscale)



ggraph(graph, "manual", x = x, y = y) + 
  geom_edge_arc(aes(color = color_edges, width = weight), alpha = 0.4, strength = 0.2, show.legend = FALSE) +
  scale_edge_width_continuous(range = c(0.1,2)) +
  scale_edge_colour_identity() +
  geom_node_point(aes(x=x, y=y, size = degree, fill = color), pch = 21, alpha = 0.9, show.legend = FALSE) +
  scale_size_continuous(range = c(0.2,13)) +
  scale_fill_identity() +
  new_scale("size") +
  geom_text_repel(data=top_nodes, aes(x=x, y=y, label = Label), size = 2, fontface="bold", alpha = 1, point.padding=NA, show.legend = FALSE) +
  geom_label_repel(data=community_labels, aes(x=x, y=y, label = Community_name, fill = color, size = Size_com), fontface="bold", alpha = 0.9, point.padding=NA, show.legend = FALSE) +
  scale_size_continuous(range = c(0.5,5)) +
  theme_void()


```



# 7-Cocitation 2000-2009

```{r fig.asp = 0.8, fig.height=5, fig.width = 7, out.width = "100%", message = FALSE, warning=FALSE, fig.align = "center"}


##### On a une colonne d'identifiant unique des articles et une colonne avec les refs biblios
##### recodées, on peut donc soumettre ça au package d'Aurelien

set.seed(12)

setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")

load("Data_5_nodes.rda")
load("Data_7_finalbase.rda")



library(readr)
library(stringr)
#library(bibliometrix)
library(tidyverse)
library(biblionetwork)
#library(devtools)
#devtools::install_github("agoutsmedt/biblionetwork")


eoeoe2<-eoeoe

simple<-unique(eoeoe2$V2)
simple<-as.data.frame(simple)

#setdiff(desco$Cartel,simple[,1])

desco<-desco[desco$Cartel!=108237,]




comp<-cbind(simple,desco$Cartel)




desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2000|2001|2002|2003|2004|2005|2006|2007|2008|2009")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1970|1971|1972|1973|1974|1975|1976|1977|1978|1979")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1980|1981|1982|1983|1984|1985|1986|1987|1988|1989")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1990|1991|1992|1993|1994|1995|1996|1997|1998|1999")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2000|2001|2002|2003|2004|2005|2006|2007|2008|2009")



desco<-desco[desco$sloubi==T,]


Cartel<-desco$Cartel

eoeoe2$toofar<-"AB"
for(i in 1:nrow(eoeoe2)){
  if(eoeoe2$V2[i]%in%Cartel){eoeoe2$toofar[i]<-T}else{eoeoe2$toofar[i]<-F}}

eoeoe2<-eoeoe2[eoeoe2$toofar==T,]

Carlito<-unique(eoeoe2$V2)

Carlito<-as.data.frame(Carlito)
Cartel<-as.data.frame(Cartel)


Cabal<-cbind(Carlito,Cartel)


eoeoe2$V2<-as.character(eoeoe2$V2)
eoeoe2$identifiant<-as.character(eoeoe2$identifiant)
desco$Cartel<-as.character(desco$Cartel)


Basefinale<-biblio_coupling(eoeoe2, source = "identifiant", ref = "V2", normalized_weight_only = FALSE, weight_threshold = 2)



#devtools::install_github("agoutsmedt/networkflow")

library(biblionetwork)
library(magrittr)
library(dplyr)
library(tidygraph)
library(networkflow)
#devtools::install_github("agoutsmedt/networkflow")

library(tidygraph)
#devtools::install_github("ParkerICI/vite")
library(vite)


Edges_coupling2<-Basefinale[,-c(4)]


Nodes_coupling2<-unique(eoeoe2$identifiant)

Nodes_coupling2<-as.data.frame(Nodes_coupling2)

Nodes_coupling2$frequence<-0
for(i in 1:nrow(Nodes_coupling2)){
  j<-which(Nodes_coupling2$Nodes_coupling2[i] == eoeoe2$identifiant)[1]
  Nodes_coupling2$frequence[i]<-eoeoe2$frequence[j]
}


Nodes_coupling2$ids<-Nodes_coupling2$Nodes_coupling2


palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

graph <- tbl_main_component(nodes = Nodes_coupling2, edges = Edges_coupling2, directed = FALSE, node_key = "Cartel", nb_components = 1)


## Varying the resolution of the algorithm results in a different partition and 
## different number of communities. A lower resolution means less communities, and conversely.
## The basic resolution of the leiden_workflow() is set by res_1 and equals 1 by default. 
## You can vary this parameter, but also try a second resolution with res_2 and a third one 
## with res_3
## On peut l'enlever avec un argument par défaut de 1


graph <- leiden_workflow(graph, res_1 = 0.5)

graph <- community_colors(graph, palette, community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree())



graph <- community_names(graph, ordering_column = "degree", naming = "ids", community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>% 
  mutate(size = frequence) # use here what you will use for the size of the nodes in the graph. Force Atlas will take care of avoiding overlapping


######## First.iter initiallement 5000, j'ai baissé pour arriver à le faire tourner


graph <- vite::complete_forceatlas2(graph, first.iter = 10000, overlap.method = "repel", overlap.iter = 1500)


top_nodes  <- top_nodes(graph, ordering_column = "degree", top_n = 10, top_n_per_com = 1)


community_labels2 <- community_labels(graph, community_name_column = "Community_name", community_size_column = "Size_com")


library(ggraph)
library(ggrepel) 
library(ggnewscale)


graph456<-as.data.frame(graph)



ggraph(graph, "manual", x = x, y = y) + 
  geom_edge_arc(aes(color = color_edges, width = weight), alpha = 0.4, strength = 0.2, show.legend = FALSE) +
  scale_edge_width_continuous(range = c(0.1,2)) +
  scale_edge_colour_identity() +
  geom_node_point(aes(x=x, y=y, size = degree, fill = color), pch = 21, alpha = 0.9, show.legend = FALSE) +
  scale_size_continuous(range = c(0.2,13)) +
  scale_fill_identity() +
  new_scale("size") +
  geom_text_repel(data=top_nodes, aes(x=x, y=y, label = Label), size = 2, fontface="bold", alpha = 1, point.padding=NA, show.legend = FALSE) +
  geom_label_repel(data=community_labels2, aes(x=x, y=y, label = Community_name, fill = color, size = Size_com), fontface="bold", alpha = 0.9, point.padding=NA, show.legend = FALSE) +
  scale_size_continuous(range = c(0.5,5)) +
  theme_void()






```


```{r}


graph123<-graph123[,c(1,9)]
graph456<-graph456[,c(1,4)]



eoeoe$comcitant<-0
for(i in 1:nrow(graph123)){
  j<-which(eoeoe$V2 == graph123$Id[i])
  eoeoe$comcitant[j]<-graph123$Com_ID[i]
}


eoeoe$comcite<-0
for(i in 1:nrow(graph456)){
  j<-which(eoeoe$identifiant == graph456$Id[i])
  eoeoe$comcite[j]<-graph456$Com_ID[i]
}



eoeoe4<-eoeoe
eoeoe4<-eoeoe4[eoeoe4$comcitant!=0,]
eoeoe4<-eoeoe4[eoeoe4$comcite!=0,]


community_labels2$ID<-gsub("-.*", "",community_labels2$Community_name)

community_labels2$IDil<-gsub(".*-", "",community_labels2$Community_name)


community_labels2$IDcompl<-"AB"
for(i in 1:nrow(community_labels2)){
  j<-which(community_labels2$IDil[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  community_labels2$IDcompl[i] <- eoeoe$V1[j[z]]
}


tableau<-as.data.frame.matrix(prop.table(table(eoeoe4$comcitant,eoeoe4$comcite),margin=1)*100)
library(dplyr)
tableau<-tableau %>% mutate_if(is.numeric, ~round(., 1))


community_labels<-community_labels[order(community_labels$identifiant),]
row.names(tableau) <- community_labels$Community_name

community_labels2<-community_labels2[order(community_labels2$Community_name),]
colnames(tableau)<- community_labels2$ID


for(i in 1:nrow(community_labels2)){
  community_labels2$IDcompl[i]<-paste(i,"-",community_labels2$IDcompl[i])
}

Legend<-community_labels2[,c(8)]

Legend<-as.data.frame(Legend)

names(Legend)[names(Legend) == "IDcompl"] <- "Complete reference of the clusters"

library(knitr)
library(kableExtra)


kable(Legend)



```

# 8- Connect the communities 2000-2009


```{r}


########################################################################################
##############################################################################################################
# Connecter les communautés -----------------------------
##############################################################################################################
##############################################################################################################


tableau %>%
  kbl() %>%
  kable_styling()


```







# 9- Bibliographic coupling 1990-1999

```{r fig.asp = 0.8, fig.height=5, fig.width = 7, out.width = "100%", message = FALSE, warning=FALSE, fig.align = "center"}




#####################################################################################################################
#####################################################################################################################
# Coupling Co-citation 2000-2009 -------------------
#####################################################################################################################
#####################################################################################################################




#####################################################################################################################
#####################################################################################################################
# Bibliographic Coupling 2000-2009----------------------------------------------------
#####################################################################################################################
#####################################################################################################################


##### On a une colonne d'identifiant unique des articles et une colonne avec les refs biblios
##### recodées, on peut donc soumettre ça au package d'Aurelien

set.seed(12)

setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")

load("Data_5_nodes.rda")
load("Data_7_finalbase.rda")


library(readr)
library(stringr)
#library(bibliometrix)
library(tidyverse)
library(biblionetwork)
#library(devtools)
#devtools::install_github("agoutsmedt/biblionetwork")


eoeoe2<-eoeoe

simple<-unique(eoeoe2$V2)
simple<-as.data.frame(simple)

#setdiff(desco$Cartel,simple[,1])

desco<-desco[desco$Cartel!=108237,]


comp<-cbind(simple,desco$Cartel)




desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1990|1991|1992|1993|1994|1995|1996|1997|1998|1999")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1970|1971|1972|1973|1974|1975|1976|1977|1978|1979|1980|1981|1982|1983|1984|1985|1986|1987|1988|1989|1990|1991|1992|1993|1994|1995|1996|1997|1998|1990|2000")

desco<-desco[desco$sloubi==T,]


Cartel<-desco$Cartel

eoeoe2$toofar<-"AB"
for(i in 1:nrow(eoeoe2)){
  if(eoeoe2$V2[i]%in%Cartel){eoeoe2$toofar[i]<-T}else{eoeoe2$toofar[i]<-F}}

eoeoe2<-eoeoe2[eoeoe2$toofar==T,]

Carlito<-unique(eoeoe2$V2)

Carlito<-as.data.frame(Carlito)
Cartel<-as.data.frame(Cartel)


Cabal<-cbind(Carlito,Cartel)


eoeoe2$V2<-as.character(eoeoe2$V2)
eoeoe2$identifiant<-as.character(eoeoe2$identifiant)
desco$Cartel<-as.character(desco$Cartel)



Basefinale<-biblio_coupling(eoeoe2, source = "V2", ref = "identifiant", normalized_weight_only = FALSE, weight_threshold = 2)



#devtools::install_github("agoutsmedt/networkflow")

library(biblionetwork)
library(magrittr)
library(dplyr)
library(tidygraph)
library(networkflow)
library(tidygraph)
#devtools::install_github("ParkerICI/vite")
library(vite)




Edges_coupling2<-Basefinale[,-c(4)]


Nodes_coupling2<-desco

Nodes_coupling2$frequence<-1

Nodes_coupling2$Datepubli<-as.character(Nodes_coupling2$Datepubli)

Nodes_coupling2$author_date<-paste(Nodes_coupling2$Cartel,Nodes_coupling2$Firstauthor,Nodes_coupling2$Datepubli)

palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

graph <- tbl_main_component(nodes = Nodes_coupling2, edges = Edges_coupling2, directed = FALSE, node_key = "Cartel", nb_components = 1)

graph <- leiden_workflow(graph, res_1 = 1)

graph <- community_colors(graph, palette, community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree())



graph <- community_names(graph, ordering_column = "degree", naming = "author_date", community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>% 
  mutate(size = degree) # use here what you will use for the size of the nodes in the graph. Force Atlas will take care of avoiding overlapping

graph <- vite::complete_forceatlas2(graph, first.iter = 10000, overlap.method = "repel", overlap.iter = 1000)



graph123<-as.data.frame(graph)



#################################################################################################################
#################################################################################################################
# On extrait les abstracts pour faire de l'analyse textuelle ---------------------------------
#################################################################################################################
#################################################################################################################


load("Data_4_Abstracts.rda")


zalerit$comcitant<-0
for(i in 1:nrow(graph123)){
  j<-which(zalerit$Cartel == graph123$Id[i])
  zalerit$comcitant[j]<-graph123$Com_ID[i]
}


library(dplyr)
library(janeaustenr) #Inutile je pense
library(tidytext)
library(gutenbergr)  #Idem
library(pdftools)
library(tidyverse)
library(qdapRegex)


zaler2<-zalerit[,c(1,3)]

zaler2<-zaler2[zaler2$comcitant!=0,]

zaler2$V1<-as.character(zaler2$V1)
zaler2$comcitant<-as.character(zaler2$comcitant)



paly<-length(table(zaler2$comcitant))


Basetotale_words <- zaler2 %>%
  unnest_tokens(word, V1) %>%
  count(comcitant, word, sort = TRUE)



# On supprime les mots de deux lettres et de une lettre
Basetotale_words$word<-rm_nchar_words(Basetotale_words$word, 2)
Basetotale_words$word<-rm_nchar_words(Basetotale_words$word, 1)


# On remplace le vide que cree l'etape precedente par des NA et on supprime les NA
Basetotale_words$word[Basetotale_words$word==""] <- NA
Basetotale_words <- na.omit(Basetotale_words)


mystopwords <- tibble(word = c("qmi","consumerswho"))


Basetotale_words <- anti_join(Basetotale_words, mystopwords,
                              by = "word")


plot_Basetotale <- Basetotale_words %>%
  bind_tf_idf(word, comcitant, n) %>%
  mutate(word = str_remove_all(word, "_")) %>%
  group_by(comcitant) %>%
  slice_max(tf_idf, n = 25) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, comcitant)) %>%
  mutate(comcitant = factor(comcitant))



palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

palette <- palette[1:paly]

#ggplot(plot_Basetotale, aes(word, tf_idf, fill = comcitant)) +
#  geom_col(show.legend = FALSE) +
#  labs(x = NULL, y = "tf-idf") +
#  facet_wrap(~comcitant, ncol = 2, scales = "free") +
#  coord_flip() +
#  scale_x_reordered() +
#  scale_fill_manual(values=c(palette))


plot_Basetotale2<-plot_Basetotale[,c(1,2)]


plot_Basetotale2$word<-str_replace(string = plot_Basetotale2$word, pattern = "___.*", replacement = "")


plot_Basetotale2$word<-toupper(plot_Basetotale2$word)

plot_Basetotale2$word<-trimws(plot_Basetotale2$word)


plot_Basetotale2$plural <- gsub('.{1}$','', plot_Basetotale2$word)


j<-unique(plot_Basetotale2$comcitant)

plot_Basetotale2$dede <- 0
for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])
  for(m in k){if(any(plot_Basetotale2$plural[m]==plot_Basetotale2$word[k])){
    z<-which(plot_Basetotale2$plural[m]==plot_Basetotale2$word[k])
    if(k[z]<m){
      plot_Basetotale2$dede[k[z]]<-10
      plot_Basetotale2$dede[m]<-28}else{
        plot_Basetotale2$dede[k[z]]<-28
        plot_Basetotale2$dede[m]<-10}
  }else{
    plot_Basetotale2$dede[m]<-plot_Basetotale2$dede[m]}}
}



plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$dede!=28,]
plot_Basetotale2<-plot_Basetotale2[,c(1,2)]



j<-unique(plot_Basetotale2$comcitant)
plot_Basetotale2$comp<-0

for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])[1:4]
  plot_Basetotale2$comp[k]<-1
}

plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$comp==T,]





for(i in 1: length(unique(plot_Basetotale2$comcitant))){
  k<-which(plot_Basetotale2$comcitant==j[i])[1]
  plot_Basetotale2$comp[k]<-paste(plot_Basetotale2$word[k],";",plot_Basetotale2$word[k+1],";",plot_Basetotale2$word[k+2],";",plot_Basetotale2$word[k+3])
}


plot_Basetotale2<-plot_Basetotale2[,c(1,3)]
plot_Basetotale2<-plot_Basetotale2[plot_Basetotale2$comp!=1,]



names(plot_Basetotale2)[names(plot_Basetotale2) == "comcitant"] <- "Com_ID"


#################################################################################################################################
#################################################################################################################################
# Fin de l'extraction des mots-clés --------------------------------------------------------------
#################################################################################################################################
#################################################################################################################################



top_nodes  <- top_nodes(graph, ordering_column = "degree", top_n = 10, top_n_per_com = 1)


community_labels <- community_labels(graph, community_name_column = "Community_name", community_size_column = "Size_com")

community_labels$identifiant<-str_sub (community_labels$Community_name, 1,2)

for(i in 1:nrow(community_labels)){
  j<-which(community_labels$identifiant[i] == plot_Basetotale2)
  community_labels$Community_name[i]<- plot_Basetotale2$comp[j]
}



library(ggraph)
library(ggrepel) 
library(ggnewscale)



ggraph(graph, "manual", x = x, y = y) + 
  geom_edge_arc(aes(color = color_edges, width = weight), alpha = 0.4, strength = 0.2, show.legend = FALSE) +
  scale_edge_width_continuous(range = c(0.1,2)) +
  scale_edge_colour_identity() +
  geom_node_point(aes(x=x, y=y, size = degree, fill = color), pch = 21, alpha = 0.9, show.legend = FALSE) +
  scale_size_continuous(range = c(0.2,13)) +
  scale_fill_identity() +
  new_scale("size") +
  geom_text_repel(data=top_nodes, aes(x=x, y=y, label = Label), size = 2, fontface="bold", alpha = 1, point.padding=NA, show.legend = FALSE) +
  geom_label_repel(data=community_labels, aes(x=x, y=y, label = Community_name, fill = color, size = Size_com), fontface="bold", alpha = 0.9, point.padding=NA, show.legend = FALSE) +
  scale_size_continuous(range = c(0.5,5)) +
  theme_void()


```



# 10-Cocitation 1990-1999

```{r fig.asp = 0.8, fig.height=5, fig.width = 7, out.width = "100%", message = FALSE, warning=FALSE, fig.align = "center"}


##### On a une colonne d'identifiant unique des articles et une colonne avec les refs biblios
##### recodées, on peut donc soumettre ça au package d'Aurelien

set.seed(12)

setwd("C:/Users/jgrad/Desktop/Network_Quality/Network_Quality")

load("Data_5_nodes.rda")
load("Data_7_finalbase.rda")



library(readr)
library(stringr)
#library(bibliometrix)
library(tidyverse)
library(biblionetwork)
#library(devtools)
#devtools::install_github("agoutsmedt/biblionetwork")


eoeoe2<-eoeoe

simple<-unique(eoeoe2$V2)
simple<-as.data.frame(simple)

#setdiff(desco$Cartel,simple[,1])

desco<-desco[desco$Cartel!=108237,]




comp<-cbind(simple,desco$Cartel)




#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2000|2001|2002|2003|2004|2005|2006|2007|2008|2009")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1970|1971|1972|1973|1974|1975|1976|1977|1978|1979")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1980|1981|1982|1983|1984|1985|1986|1987|1988|1989")
desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "1990|1991|1992|1993|1994|1995|1996|1997|1998|1999")
#desco$sloubi<-str_detect (string = desco$Datepubli, pattern = "2000|2001|2002|2003|2004|2005|2006|2007|2008|2009")



desco<-desco[desco$sloubi==T,]


Cartel<-desco$Cartel

eoeoe2$toofar<-"AB"
for(i in 1:nrow(eoeoe2)){
  if(eoeoe2$V2[i]%in%Cartel){eoeoe2$toofar[i]<-T}else{eoeoe2$toofar[i]<-F}}

eoeoe2<-eoeoe2[eoeoe2$toofar==T,]

Carlito<-unique(eoeoe2$V2)

Carlito<-as.data.frame(Carlito)
Cartel<-as.data.frame(Cartel)


Cabal<-cbind(Carlito,Cartel)


eoeoe2$V2<-as.character(eoeoe2$V2)
eoeoe2$identifiant<-as.character(eoeoe2$identifiant)
desco$Cartel<-as.character(desco$Cartel)


Basefinale<-biblio_coupling(eoeoe2, source = "identifiant", ref = "V2", normalized_weight_only = FALSE, weight_threshold = 2)



#devtools::install_github("agoutsmedt/networkflow")

library(biblionetwork)
library(magrittr)
library(dplyr)
library(tidygraph)
library(networkflow)
#devtools::install_github("agoutsmedt/networkflow")

library(tidygraph)
#devtools::install_github("ParkerICI/vite")
library(vite)


Edges_coupling2<-Basefinale[,-c(4)]


Nodes_coupling2<-unique(eoeoe2$identifiant)

Nodes_coupling2<-as.data.frame(Nodes_coupling2)

Nodes_coupling2$frequence<-0
for(i in 1:nrow(Nodes_coupling2)){
  j<-which(Nodes_coupling2$Nodes_coupling2[i] == eoeoe2$identifiant)[1]
  Nodes_coupling2$frequence[i]<-eoeoe2$frequence[j]
}


Nodes_coupling2$ids<-Nodes_coupling2$Nodes_coupling2


palette <- c("#1969B3","#01A5D8","#DA3E61","#3CB95F","#E0AF0C","#E25920","#6C7FC9","#DE9493","#CD242E","#6F4288","#B2EEF8","#7FF6FD","#FDB8D6","#8BF9A9","#FEF34A","#FEC57D","#DAEFFB","#FEE3E1","#FBB2A7","#EFD7F2","#5CAADA","#37D4F5","#F5779B","#62E186","#FBDA28","#FB8F4A","#A4B9EA","#FAC2C0","#EB6466","#AD87BC","#0B3074","#00517C","#871B2A","#1A6029","#7C4B05","#8A260E","#2E3679","#793F3F","#840F14","#401C56","#003C65","#741A09","#602A2A","#34134A","#114A1B","#27DDD1","#27DD8D","#4ADD27","#D3DD27","#DDA427","#DF2935","#DD27BC","#BA27DD","#3227DD","#2761DD","#27DDD1")

graph <- tbl_main_component(nodes = Nodes_coupling2, edges = Edges_coupling2, directed = FALSE, node_key = "Cartel", nb_components = 1)


## Varying the resolution of the algorithm results in a different partition and 
## different number of communities. A lower resolution means less communities, and conversely.
## The basic resolution of the leiden_workflow() is set by res_1 and equals 1 by default. 
## You can vary this parameter, but also try a second resolution with res_2 and a third one 
## with res_3
## On peut l'enlever avec un argument par défaut de 1


graph <- leiden_workflow(graph, res_1 = 0.5)

graph <- community_colors(graph, palette, community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>%
  mutate(degree = centrality_degree())



graph <- community_names(graph, ordering_column = "degree", naming = "ids", community_column = "Com_ID")


graph <- graph %>%
  activate(nodes) %>% 
  mutate(size = frequence) # use here what you will use for the size of the nodes in the graph. Force Atlas will take care of avoiding overlapping


######## First.iter initiallement 5000, j'ai baissé pour arriver à le faire tourner


graph <- vite::complete_forceatlas2(graph, first.iter = 10000, overlap.method = "repel", overlap.iter = 1500)


top_nodes  <- top_nodes(graph, ordering_column = "degree", top_n = 10, top_n_per_com = 1)


community_labels2 <- community_labels(graph, community_name_column = "Community_name", community_size_column = "Size_com")


library(ggraph)
library(ggrepel) 
library(ggnewscale)


graph456<-as.data.frame(graph)



ggraph(graph, "manual", x = x, y = y) + 
  geom_edge_arc(aes(color = color_edges, width = weight), alpha = 0.4, strength = 0.2, show.legend = FALSE) +
  scale_edge_width_continuous(range = c(0.1,2)) +
  scale_edge_colour_identity() +
  geom_node_point(aes(x=x, y=y, size = degree, fill = color), pch = 21, alpha = 0.9, show.legend = FALSE) +
  scale_size_continuous(range = c(0.2,13)) +
  scale_fill_identity() +
  new_scale("size") +
  geom_text_repel(data=top_nodes, aes(x=x, y=y, label = Label), size = 2, fontface="bold", alpha = 1, point.padding=NA, show.legend = FALSE) +
  geom_label_repel(data=community_labels2, aes(x=x, y=y, label = Community_name, fill = color, size = Size_com), fontface="bold", alpha = 0.9, point.padding=NA, show.legend = FALSE) +
  scale_size_continuous(range = c(0.5,5)) +
  theme_void()






```


```{r}


graph123<-graph123[,c(1,9)]
graph456<-graph456[,c(1,4)]



eoeoe$comcitant<-0
for(i in 1:nrow(graph123)){
  j<-which(eoeoe$V2 == graph123$Id[i])
  eoeoe$comcitant[j]<-graph123$Com_ID[i]
}


eoeoe$comcite<-0
for(i in 1:nrow(graph456)){
  j<-which(eoeoe$identifiant == graph456$Id[i])
  eoeoe$comcite[j]<-graph456$Com_ID[i]
}



eoeoe4<-eoeoe
eoeoe4<-eoeoe4[eoeoe4$comcitant!=0,]
eoeoe4<-eoeoe4[eoeoe4$comcite!=0,]


community_labels2$ID<-gsub("-.*", "",community_labels2$Community_name)

community_labels2$IDil<-gsub(".*-", "",community_labels2$Community_name)


community_labels2$IDcompl<-"AB"
for(i in 1:nrow(community_labels2)){
  j<-which(community_labels2$IDil[i] == eoeoe$identifiant)
  z<-which(paste(eoeoe$Firstauthor[j],eoeoe$Datepubli[j],eoeoe$Issue[j],eoeoe$Page[j])==eoeoe$identifiant[j])[1]
  community_labels2$IDcompl[i] <- eoeoe$V1[j[z]]
}


tableau<-as.data.frame.matrix(prop.table(table(eoeoe4$comcitant,eoeoe4$comcite),margin=1)*100)
library(dplyr)
tableau<-tableau %>% mutate_if(is.numeric, ~round(., 1))


community_labels<-community_labels[order(community_labels$identifiant),]
row.names(tableau) <- community_labels$Community_name

community_labels2<-community_labels2[order(community_labels2$Community_name),]
colnames(tableau)<- community_labels2$ID


for(i in 1:nrow(community_labels2)){
  community_labels2$IDcompl[i]<-paste(i,"-",community_labels2$IDcompl[i])
}

Legend<-community_labels2[,c(8)]

Legend<-as.data.frame(Legend)

names(Legend)[names(Legend) == "IDcompl"] <- "Complete reference of the clusters"

library(knitr)
library(kableExtra)


kable(Legend)



```

# 11- Connect the communities 1990-1999


```{r}


########################################################################################
##############################################################################################################
# Connecter les communautés -----------------------------
##############################################################################################################
##############################################################################################################


tableau %>%
  kbl() %>%
  kable_styling()


```










